#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k15m-irace-1585334-1585338/fashion-mnist-3f2k15m-irace-1585337-val-%A-%a

CONFIGS=("166  --dataset fashion-mnist --job_id 1585337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.3015 --kernel poly --degree 2 --gamma -0.645"
"200  --dataset fashion-mnist --job_id 1585337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.5028 --kernel poly --degree 2 --gamma -0.0224"
"144  --dataset fashion-mnist --job_id 1585337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.097 --kernel linear"
"295  --dataset fashion-mnist --job_id 1585337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.2036 --kernel poly --degree 2 --gamma -2.3324"
"278  --dataset fashion-mnist --job_id 1585337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.0295 --kernel poly --degree 2 --gamma -2.1593"
"265  --dataset fashion-mnist --job_id 1585337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -3.6365 --kernel poly --degree 2 --gamma -0.1953"
"358  --dataset fashion-mnist --job_id 1585337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.8867 --kernel poly --degree 2 --gamma -3.1239"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
