#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k15m-irace-1585334-1585338/fashion-mnist-3f2k15m-irace-1585334-val-%A-%a

CONFIGS=("158  --dataset fashion-mnist --job_id 1585334 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling True --algorithm SVM --C 0.8096 --kernel rbf --gamma -3.0424"
"43   --dataset fashion-mnist --job_id 1585334 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.1139 --kernel rbf --gamma -3.5673"
"231  --dataset fashion-mnist --job_id 1585334 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 3.5618 --kernel rbf --gamma -2.647"
"157  --dataset fashion-mnist --job_id 1585334 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.6591 --kernel rbf --gamma -3.403"
"165  --dataset fashion-mnist --job_id 1585334 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 2.9104 --kernel rbf --gamma -3.4386"
"100  --dataset fashion-mnist --job_id 1585334 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 3.9882 --kernel rbf --gamma -3.7947"
"86   --dataset fashion-mnist --job_id 1585334 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction FastICA --ext_components 0.0816 --ica_algorithm parallel --ica_fun logcosh --scaling False --algorithm MLP --solver lbfgs --alpha -0.1389 --hidden_layers 1 --neurons1 218 --activation tanh"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
