#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-5
#SBATCH --job-name=fashion-mnist-3f2k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k15m-irace-1585334-1585338/fashion-mnist-3f2k15m-irace-1585338-val-%A-%a

CONFIGS=("167  --dataset fashion-mnist --job_id 1585338 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.7049 --kernel poly --degree 1 --gamma -0.6821"
"287  --dataset fashion-mnist --job_id 1585338 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.1804 --kernel poly --degree 2 --gamma -0.2874"
"274  --dataset fashion-mnist --job_id 1585338 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 2.1032 --kernel poly --degree 2 --gamma 0.1082"
"328  --dataset fashion-mnist --job_id 1585338 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.8941 --kernel poly --degree 2 --gamma -1.46"
"316  --dataset fashion-mnist --job_id 1585338 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.4906 --kernel poly --degree 2 --gamma -1.3336"
"353  --dataset fashion-mnist --job_id 1585338 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -3.0789 --kernel poly --degree 2 --gamma -0.5229"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
