#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k15m-irace-1585334-1585338/fashion-mnist-3f2k15m-irace-1585336-val-%A-%a

CONFIGS=("329  --dataset fashion-mnist --job_id 1585336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C 1.9959 --kernel poly --degree 2 --gamma -0.9237"
"319  --dataset fashion-mnist --job_id 1585336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C 2.1941 --kernel poly --degree 2 --gamma -2.7811"
"344  --dataset fashion-mnist --job_id 1585336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C -3.5678 --kernel poly --degree 2 --gamma -1.162"
"345  --dataset fashion-mnist --job_id 1585336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C -0.65 --kernel poly --degree 2 --gamma 0.907"
"358  --dataset fashion-mnist --job_id 1585336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C 0.8064 --kernel poly --degree 2 --gamma -1.3283"
"217  --dataset fashion-mnist --job_id 1585336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C 1.2266 --kernel poly --degree 2 --gamma -4.1996"
"330  --dataset fashion-mnist --job_id 1585336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C -0.4476 --kernel poly --degree 2 --gamma -0.0077"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
