#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1586343-1586347/cifar100-1f2k10m-irace-1586346-val-%A-%a

CONFIGS=("282  --dataset cifar100 --job_id 1586346 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 52 --scaling False --algorithm KNeighbors --n_neighbors 20 --weights distance"
"275  --dataset cifar100 --job_id 1586346 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 56 --scaling False --algorithm KNeighbors --n_neighbors 21 --weights distance"
"230  --dataset cifar100 --job_id 1586346 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 64 --scaling False --algorithm KNeighbors --n_neighbors 18 --weights distance"
"199  --dataset cifar100 --job_id 1586346 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 77 --scaling False --algorithm KNeighbors --n_neighbors 18 --weights distance"
"306  --dataset cifar100 --job_id 1586346 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 39 --scaling False --algorithm KNeighbors --n_neighbors 14 --weights distance"
"312  --dataset cifar100 --job_id 1586346 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 78 --scaling False --algorithm KNeighbors --n_neighbors 14 --weights distance"
"294  --dataset cifar100 --job_id 1586346 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 62 --scaling False --algorithm KNeighbors --n_neighbors 33 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
