#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1586343-1586347/cifar100-1f2k10m-irace-1586345-val-%A-%a

CONFIGS=("260  --dataset cifar100 --job_id 1586345 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0108 --whiten True --svd_solver full --scaling False --algorithm LogisticRegression --lr_C -2.6523 --lr_solver newton-cg --multi_class multinomial --max_iter 328"
"138  --dataset cifar100 --job_id 1586345 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0124 --ica_algorithm deflation --ica_fun cube --scaling False --algorithm LogisticRegression --lr_C -0.6319 --lr_solver newton-cg --multi_class multinomial --max_iter 230"
"236  --dataset cifar100 --job_id 1586345 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0188 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 65 --scaling False --algorithm KNeighbors --n_neighbors 58 --weights uniform"
"95   --dataset cifar100 --job_id 1586345 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0868 --whiten True --svd_solver full --scaling False --algorithm LogisticRegression --lr_C -2.2438 --lr_solver newton-cg --multi_class multinomial --max_iter 524"
"237  --dataset cifar100 --job_id 1586345 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 39 --scaling False --algorithm KNeighbors --n_neighbors 57 --weights distance"
"318  --dataset cifar100 --job_id 1586345 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0362 --whiten True --svd_solver full --scaling False --algorithm LogisticRegression --lr_C -3.831 --lr_solver newton-cg --multi_class multinomial --max_iter 308"
"329  --dataset cifar100 --job_id 1586345 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 29 --scaling False --algorithm KNeighbors --n_neighbors 61 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
