#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1586343-1586347/cifar100-1f2k10m-irace-1586343-val-%A-%a

CONFIGS=("287  --dataset cifar100 --job_id 1586343 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 84 --scaling True --algorithm KNeighbors --n_neighbors 11 --weights distance"
"313  --dataset cifar100 --job_id 1586343 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 72 --scaling True --algorithm KNeighbors --n_neighbors 13 --weights distance"
"270  --dataset cifar100 --job_id 1586343 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 70 --scaling True --algorithm KNeighbors --n_neighbors 14 --weights distance"
"280  --dataset cifar100 --job_id 1586343 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 46 --scaling True --algorithm KNeighbors --n_neighbors 23 --weights distance"
"283  --dataset cifar100 --job_id 1586343 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 68 --scaling True --algorithm KNeighbors --n_neighbors 11 --weights distance"
"127  --dataset cifar100 --job_id 1586343 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 51 --scaling True --algorithm KNeighbors --n_neighbors 38 --weights distance"
"285  --dataset cifar100 --job_id 1586343 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 58 --scaling True --algorithm KNeighbors --n_neighbors 21 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
