#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-2
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1586343-1586347/cifar100-1f2k10m-irace-1586347-val-%A-%a

CONFIGS=("349  --dataset cifar100 --job_id 1586347 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C 4.4268 --kernel linear"
"358  --dataset cifar100 --job_id 1586347 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C 2.127 --kernel linear"
"359  --dataset cifar100 --job_id 1586347 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C 3.8773 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
