#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1554124-1554128/cifar100-3f2k30m-irace-1554128-val-%A-%a

CONFIGS=("342  --dataset cifar100 --job_id 1554128 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C -2.02 --kernel linear"
"354  --dataset cifar100 --job_id 1554128 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 0.5294 --kernel linear"
"323  --dataset cifar100 --job_id 1554128 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 4.1283 --kernel linear"
"346  --dataset cifar100 --job_id 1554128 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 4.2279 --kernel linear"
"352  --dataset cifar100 --job_id 1554128 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 4.5018 --kernel linear"
"309  --dataset cifar100 --job_id 1554128 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C -0.0328 --kernel linear"
"360  --dataset cifar100 --job_id 1554128 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 3.7239 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
