#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-4
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1554124-1554128/cifar100-3f2k30m-irace-1554127-val-%A-%a

CONFIGS=("314  --dataset cifar100 --job_id 1554127 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0134 --whiten False --svd_solver auto --scaling False --algorithm KNeighbors --n_neighbors 28 --weights uniform"
"180  --dataset cifar100 --job_id 1554127 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.1536 --whiten False --svd_solver auto --scaling False --algorithm KNeighbors --n_neighbors 98 --weights uniform"
"178  --dataset cifar100 --job_id 1554127 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0585 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 3 --scaling False --algorithm RandomForest --rf_estimators 459 --criterion_classification gini --max_features 0.3714 --max_depth none --min_samples_leaf 0.0795"
"345  --dataset cifar100 --job_id 1554127 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.4027 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 2 --scaling False --algorithm RandomForest --rf_estimators 478 --criterion_classification gini --max_features 0.2512 --max_depth none --min_samples_leaf 0.0573"
"349  --dataset cifar100 --job_id 1554127 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0282 --whiten False --svd_solver auto --scaling False --algorithm KNeighbors --n_neighbors 43 --weights uniform"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
