#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1554124-1554128/cifar100-3f2k30m-irace-1554126-val-%A-%a

CONFIGS=("295  --dataset cifar100 --job_id 1554126 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -3.4721 --kernel linear"
"330  --dataset cifar100 --job_id 1554126 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.6816 --kernel linear"
"322  --dataset cifar100 --job_id 1554126 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -3.3363 --kernel linear"
"331  --dataset cifar100 --job_id 1554126 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.2532 --kernel linear"
"340  --dataset cifar100 --job_id 1554126 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.8325 --kernel linear"
"337  --dataset cifar100 --job_id 1554126 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -3.3793 --kernel linear"
"345  --dataset cifar100 --job_id 1554126 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -3.203 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
