#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-3
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1554124-1554128/cifar100-3f2k30m-irace-1554125-val-%A-%a

CONFIGS=("269  --dataset cifar100 --job_id 1554125 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0165 --ica_algorithm parallel --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 32 --scaling False --algorithm SVM --C -0.5008 --kernel sigmoid --gamma -2.2908"
"304  --dataset cifar100 --job_id 1554125 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0253 --ica_algorithm parallel --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 51 --scaling False --algorithm SVM --C -1.4482 --kernel sigmoid --gamma -1.226"
"312  --dataset cifar100 --job_id 1554125 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0701 --ica_algorithm parallel --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 21 --scaling False --algorithm SVM --C -2.1008 --kernel sigmoid --gamma -3.2578"
"338  --dataset cifar100 --job_id 1554125 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.014 --ica_algorithm parallel --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 40 --scaling False --algorithm SVM --C -0.5361 --kernel sigmoid --gamma -4.669"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
