#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1554124-1554128/cifar100-3f2k30m-irace-1554124-val-%A-%a

CONFIGS=("260  --dataset cifar100 --job_id 1554124 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C 2.0409 --kernel linear"
"228  --dataset cifar100 --job_id 1554124 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C -1.1053 --kernel linear"
"287  --dataset cifar100 --job_id 1554124 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -0.9501 --kernel linear"
"288  --dataset cifar100 --job_id 1554124 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.677 --kernel linear"
"292  --dataset cifar100 --job_id 1554124 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C -2.9139 --kernel linear"
"214  --dataset cifar100 --job_id 1554124 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C -0.0028 --kernel linear"
"290  --dataset cifar100 --job_id 1554124 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 4.2676 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
