#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-3f2k15m-irace-val
#SBATCH --output=validation/cifar10-3f2k15m-irace-1585118-1585122/cifar10-3f2k15m-irace-1585119-val-%A-%a

CONFIGS=("187  --dataset cifar10 --job_id 1585119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 23 --scaling False --algorithm AdaBoost --ab_estimators 287 --ab_learning_rate 0.2179"
"341  --dataset cifar10 --job_id 1585119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 12 --weights uniform"
"330  --dataset cifar10 --job_id 1585119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 8 --weights uniform"
"331  --dataset cifar10 --job_id 1585119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 16 --weights uniform"
"320  --dataset cifar10 --job_id 1585119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 20 --weights uniform"
"346  --dataset cifar10 --job_id 1585119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 41 --scaling False --algorithm AdaBoost --ab_estimators 298 --ab_learning_rate 0.3832"
"347  --dataset cifar10 --job_id 1585119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 9 --weights uniform"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
