#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-5
#SBATCH --job-name=cifar10-3f2k15m-irace-val
#SBATCH --output=validation/cifar10-3f2k15m-irace-1585118-1585122/cifar10-3f2k15m-irace-1585121-val-%A-%a

CONFIGS=("193  --dataset cifar10 --job_id 1585121 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -3.5933 --lr_solver lbfgs --multi_class multinomial --max_iter 151"
"295  --dataset cifar10 --job_id 1585121 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -0.2381 --lr_solver lbfgs --multi_class multinomial --max_iter 101"
"260  --dataset cifar10 --job_id 1585121 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -3.0992 --lr_solver lbfgs --multi_class multinomial --max_iter 117"
"305  --dataset cifar10 --job_id 1585121 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -1.7262 --lr_solver lbfgs --multi_class multinomial --max_iter 119"
"340  --dataset cifar10 --job_id 1585121 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -0.6285 --lr_solver lbfgs --multi_class multinomial --max_iter 107"
"313  --dataset cifar10 --job_id 1585121 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -1.9289 --lr_solver lbfgs --multi_class multinomial --max_iter 107"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
