#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-2
#SBATCH --job-name=cifar10-3f2k15m-irace-val
#SBATCH --output=validation/cifar10-3f2k15m-irace-1585118-1585122/cifar10-3f2k15m-irace-1585118-val-%A-%a

CONFIGS=("218  --dataset cifar10 --job_id 1585118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 97 --scaling True --algorithm LogisticRegression --lr_C -3.5254 --lr_solver newton-cg --multi_class multinomial --max_iter 813"
"346  --dataset cifar10 --job_id 1585118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 95 --scaling True --algorithm LogisticRegression --lr_C -3.5629 --lr_solver newton-cg --multi_class multinomial --max_iter 652"
"343  --dataset cifar10 --job_id 1585118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 89 --scaling True --algorithm LogisticRegression --lr_C -3.4962 --lr_solver newton-cg --multi_class multinomial --max_iter 789"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
