#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-3
#SBATCH --job-name=cifar10-3f2k15m-irace-val
#SBATCH --output=validation/cifar10-3f2k15m-irace-1585118-1585122/cifar10-3f2k15m-irace-1585120-val-%A-%a

CONFIGS=("355  --dataset cifar10 --job_id 1585120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.0967 --lr_solver lbfgs --multi_class ovr --max_iter 490"
"347  --dataset cifar10 --job_id 1585120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.0609 --lr_solver lbfgs --multi_class ovr --max_iter 546"
"345  --dataset cifar10 --job_id 1585120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.5559 --lr_solver lbfgs --multi_class ovr --max_iter 729"
"346  --dataset cifar10 --job_id 1585120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.6102 --lr_solver lbfgs --multi_class ovr --max_iter 474"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
