#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1545510-1545514/fashion-mnist-1f2k10m-irace-1545511-val-%A-%a

CONFIGS=("280  --dataset fashion-mnist --job_id 1545511 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.7539 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 80 --scaling False --algorithm SVM --C 2.8855 --kernel rbf --gamma -2.5708"
"251  --dataset fashion-mnist --job_id 1545511 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.7037 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 77 --scaling False --algorithm SVM --C 2.0461 --kernel rbf --gamma -2.6515"
"328  --dataset fashion-mnist --job_id 1545511 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.8913 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 76 --scaling False --algorithm SVM --C 4.1695 --kernel rbf --gamma -2.7799"
"246  --dataset fashion-mnist --job_id 1545511 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.3274 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 86 --scaling False --algorithm SVM --C 1.3351 --kernel rbf --gamma -3.3213"
"178  --dataset fashion-mnist --job_id 1545511 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.5345 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 62 --scaling False --algorithm SVM --C 4.6871 --kernel rbf --gamma -2.3863"
"212  --dataset fashion-mnist --job_id 1545511 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.225 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 66 --scaling False --algorithm SVM --C 2.7795 --kernel rbf --gamma -2.3224"
"160  --dataset fashion-mnist --job_id 1545511 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.2795 --kernel rbf --gamma -2.9904"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
