#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-3
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1545510-1545514/fashion-mnist-1f2k10m-irace-1545513-val-%A-%a

CONFIGS=("275  --dataset fashion-mnist --job_id 1545513 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 93 --scaling False --algorithm SVM --C 0.8369 --kernel rbf --gamma -3.115"
"206  --dataset fashion-mnist --job_id 1545513 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 80 --scaling False --algorithm SVM --C 4.1877 --kernel rbf --gamma -2.6959"
"323  --dataset fashion-mnist --job_id 1545513 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 72 --scaling False --algorithm SVM --C 0.4011 --kernel rbf --gamma -2.4762"
"322  --dataset fashion-mnist --job_id 1545513 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 96 --scaling False --algorithm SVM --C 0.898 --kernel rbf --gamma -3.2578"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
