#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1545510-1545514/fashion-mnist-1f2k10m-irace-1545514-val-%A-%a

CONFIGS=("342  --dataset fashion-mnist --job_id 1545514 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1152 --kernel linear"
"350  --dataset fashion-mnist --job_id 1545514 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1951 --kernel linear"
"294  --dataset fashion-mnist --job_id 1545514 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.3535 --kernel linear"
"305  --dataset fashion-mnist --job_id 1545514 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.0163 --kernel linear"
"284  --dataset fashion-mnist --job_id 1545514 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -1.9956 --kernel linear"
"368  --dataset fashion-mnist --job_id 1545514 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.5151 --kernel linear"
"372  --dataset fashion-mnist --job_id 1545514 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -1.8456 --kernel linear"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
