#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --array=0-6
#SBATCH --mem-per-cpu=32G
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1545510-1545514/fashion-mnist-1f2k10m-irace-1545510-val-%A-%a

CONFIGS=("239  --dataset fashion-mnist --job_id 1545510 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver adam --alpha -3.4172 --learning_rate_init -2.2944 --hidden_layers 1 --neurons1 332 --activation logistic"
"298  --dataset fashion-mnist --job_id 1545510 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 75 --scaling True --algorithm SVM --C 1.3285 --kernel poly --degree 2 --gamma -2.3848"
"140  --dataset fashion-mnist --job_id 1545510 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 86 --scaling True --algorithm SVM --C 2.3236 --kernel poly --degree 2 --gamma -1.4664"
"297  --dataset fashion-mnist --job_id 1545510 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 65 --scaling True --algorithm SVM --C 2.8097 --kernel poly --degree 2 --gamma -0.5883"
"337  --dataset fashion-mnist --job_id 1545510 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver adam --alpha -2.9754 --learning_rate_init -1.9197 --hidden_layers 1 --neurons1 203 --activation logistic"
"331  --dataset fashion-mnist --job_id 1545510 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver adam --alpha -2.9193 --learning_rate_init -2.294 --hidden_layers 1 --neurons1 108 --activation logistic"
"367  --dataset fashion-mnist --job_id 1545510 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver adam --alpha -2.9492 --learning_rate_init -2.2019 --hidden_layers 1 --neurons1 165 --activation logistic"
)


srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
