#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-3
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1545510-1545514/fashion-mnist-1f2k10m-irace-1545512-val-%A-%a

CONFIGS=("364  --dataset fashion-mnist --job_id 1545512 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -3.3757 --kernel poly --degree 1 --gamma -2.4601"
"252  --dataset fashion-mnist --job_id 1545512 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 2.9746 --kernel poly --degree 2 --gamma -0.0747"
"315  --dataset fashion-mnist --job_id 1545512 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.7876 --kernel poly --degree 2 --gamma -2.1587"
"191  --dataset fashion-mnist --job_id 1545512 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -2.8959 --kernel poly --degree 1 --gamma -3.2958"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
