#!/bin/bash
#SBATCH --time=0-1:00
#SBATCH --job-name=isklearn
#SBATCH --cpus-per-task=8
DATASET="$1"
irace -s scenario.txt -p ${DATASET}/parameters.txt --log-file "./output/${DATASET}_irace.Rdata"
# sbatch --output isklearn_mnist_%j.out batch_script mnist
# --recovery-file "./output/${DATASET}_irace.Rdata"