#!/bin/bash
./check -d $1 -m 3 -e 2000 -c 15 -r 5
# ./check -d $1 -m 3 -e 5000 -c 15 -r 5
# ./check -d $1 -m 3 -e 2000 -c 30 -r 5
./check -d $1 -m 1 -e 2000 -c 10 -r 5
# ./check -d $1 -m 1 -e 5000 -c 10 -r 5
# ./check -d $1 -m 1 -e 2000 -c 20 -r 5