#!/bin/bash
#SBATCH --time=0-1:00
#SBATCH --job-name=viskl
#SBATCH --cpus-per-task=8
#SBATCH --output=mnist_validation_%j.out
python mnist/validation.py --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 4.06 --kernel poly --degree 5 --gamma -1.51