#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=fashion-mnist-3f2k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k15m-irace-1545495-1545499/fashion-mnist-3f2k15m-irace-1545495-val-%A-%a

CONFIGS=("343  --dataset fashion-mnist --job_id 1545495 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7249 --lr_solver lbfgs --multi_class multinomial --max_iter 960"
"240  --dataset fashion-mnist --job_id 1545495 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.8104 --lr_solver lbfgs --multi_class multinomial --max_iter 872"
"354  --dataset fashion-mnist --job_id 1545495 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7837 --lr_solver lbfgs --multi_class multinomial --max_iter 174"
"257  --dataset fashion-mnist --job_id 1545495 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7118 --lr_solver lbfgs --multi_class multinomial --max_iter 143"
"362  --dataset fashion-mnist --job_id 1545495 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.8788 --lr_solver lbfgs --multi_class multinomial --max_iter 966"
"359  --dataset fashion-mnist --job_id 1545495 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7312 --lr_solver lbfgs --multi_class multinomial --max_iter 653"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
