#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-1
#SBATCH --job-name=fashion-mnist-3f2k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k15m-irace-1545495-1545499/fashion-mnist-3f2k15m-irace-1545497-val-%A-%a

CONFIGS=("311  --dataset fashion-mnist --job_id 1545497 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 4.6626 --kernel rbf --gamma -2.7583"
"368  --dataset fashion-mnist --job_id 1545497 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.2231 --kernel rbf --gamma -3.7974"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
