#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k15m-irace-1545495-1545499/fashion-mnist-3f2k15m-irace-1545496-val-%A-%a

CONFIGS=("338  --dataset fashion-mnist --job_id 1545496 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 70 --scaling False --algorithm SVM --C -1.4942 --kernel linear"
"270  --dataset fashion-mnist --job_id 1545496 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 79 --scaling False --algorithm SVM --C -1.3793 --kernel linear"
"165  --dataset fashion-mnist --job_id 1545496 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 68 --scaling False --algorithm KNeighbors --n_neighbors 8 --weights uniform"
"115  --dataset fashion-mnist --job_id 1545496 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.0375 --whiten False --svd_solver arpack --scaling True --algorithm KNeighbors --n_neighbors 5 --weights uniform"
"303  --dataset fashion-mnist --job_id 1545496 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 78 --scaling False --algorithm KNeighbors --n_neighbors 8 --weights uniform"
"151  --dataset fashion-mnist --job_id 1545496 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 68 --scaling False --algorithm KNeighbors --n_neighbors 11 --weights uniform"
"9    --dataset fashion-mnist --job_id 1545496 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 89 --scaling False --algorithm KNeighbors --n_neighbors 3 --weights uniform"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
