#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-1f2k10m-irace-val
#SBATCH --output=validation/svhn-1f2k10m-irace-1547594-1547598/svhn-1f2k10m-irace-1547597-val-%A-%a

CONFIGS=("327  --dataset svhn --job_id 1547597 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.4121 --max_depth value --max_depth_value 28 --min_samples_leaf 0.0115"
"221  --dataset svhn --job_id 1547597 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.4959 --max_depth value --max_depth_value 25 --min_samples_leaf 0.0173"
"313  --dataset svhn --job_id 1547597 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.8411 --max_depth value --max_depth_value 22 --min_samples_leaf 0.0173"
"167  --dataset svhn --job_id 1547597 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.4778 --max_depth value --max_depth_value 15 --min_samples_leaf 0.0327"
"169  --dataset svhn --job_id 1547597 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.134 --whiten True --svd_solver auto --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.5315 --max_depth none --max_depth_value 16 --min_samples_leaf 0.0184"
"196  --dataset svhn --job_id 1547597 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0306 --whiten True --svd_solver randomized --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling True --algorithm AdaBoost --ab_estimators 176 --ab_learning_rate 0.4685"
"362  --dataset svhn --job_id 1547597 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.8845 --max_depth value --max_depth_value 28 --min_samples_leaf 0.012"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
