#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-1f2k10m-irace-val
#SBATCH --output=validation/svhn-1f2k10m-irace-1547594-1547598/svhn-1f2k10m-irace-1547594-val-%A-%a

CONFIGS=("320  --dataset svhn --job_id 1547594 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 30 --scaling True --algorithm KNeighbors --n_neighbors 10 --weights distance"
"242  --dataset svhn --job_id 1547594 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 27 --scaling True --algorithm KNeighbors --n_neighbors 8 --weights distance"
"348  --dataset svhn --job_id 1547594 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 27 --scaling True --algorithm KNeighbors --n_neighbors 7 --weights distance"
"296  --dataset svhn --job_id 1547594 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 31 --scaling True --algorithm KNeighbors --n_neighbors 15 --weights distance"
"354  --dataset svhn --job_id 1547594 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 15 --scaling True --algorithm KNeighbors --n_neighbors 8 --weights distance"
"313  --dataset svhn --job_id 1547594 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 34 --scaling True --algorithm KNeighbors --n_neighbors 9 --weights distance"
"293  --dataset svhn --job_id 1547594 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 34 --scaling True --algorithm KNeighbors --n_neighbors 10 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
