#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-3
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1540456-1540460/cifar10-1f5k10m-irace-1540460-val-%A-%a

CONFIGS=("491  --dataset cifar10 --job_id 1540460 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.0196 --whiten True --svd_solver auto --scaling True --algorithm LogisticRegression --lr_C -2.3088 --lr_solver sag --multi_class multinomial --max_iter 480"
"933  --dataset cifar10 --job_id 1540460 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.0207 --whiten True --svd_solver randomized --scaling True --algorithm LogisticRegression --lr_C -1.6286 --lr_solver sag --multi_class multinomial --max_iter 880"
"837  --dataset cifar10 --job_id 1540460 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.0269 --whiten True --svd_solver randomized --scaling True --algorithm LogisticRegression --lr_C -3.3277 --lr_solver sag --multi_class multinomial --max_iter 267"
"878  --dataset cifar10 --job_id 1540460 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.0271 --whiten True --svd_solver auto --scaling True --algorithm LogisticRegression --lr_C -2.0308 --lr_solver sag --multi_class multinomial --max_iter 636"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
