#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1540456-1540460/cifar10-1f5k10m-irace-1540457-val-%A-%a

CONFIGS=("845  --dataset cifar10 --job_id 1540457 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2441 --lr_solver lbfgs --multi_class ovr --max_iter 914"
"791  --dataset cifar10 --job_id 1540457 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2899 --lr_solver lbfgs --multi_class multinomial --max_iter 181"
"490  --dataset cifar10 --job_id 1540457 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2997 --lr_solver lbfgs --multi_class ovr --max_iter 520"
"671  --dataset cifar10 --job_id 1540457 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2809 --lr_solver lbfgs --multi_class ovr --max_iter 691"
"689  --dataset cifar10 --job_id 1540457 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2102 --lr_solver lbfgs --multi_class ovr --max_iter 728"
"825  --dataset cifar10 --job_id 1540457 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.1641 --lr_solver lbfgs --multi_class ovr --max_iter 907"
"841  --dataset cifar10 --job_id 1540457 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.077 --lr_solver lbfgs --multi_class ovr --max_iter 520"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
