#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1540456-1540460/cifar10-1f5k10m-irace-1540458-val-%A-%a

CONFIGS=("669  --dataset cifar10 --job_id 1540458 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2405 --lr_solver lbfgs --multi_class ovr --max_iter 540"
"882  --dataset cifar10 --job_id 1540458 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.242 --lr_solver lbfgs --multi_class ovr --max_iter 509"
"873  --dataset cifar10 --job_id 1540458 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2813 --lr_solver lbfgs --multi_class ovr --max_iter 623"
"868  --dataset cifar10 --job_id 1540458 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.204 --lr_solver lbfgs --multi_class ovr --max_iter 440"
"791  --dataset cifar10 --job_id 1540458 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.3592 --lr_solver lbfgs --multi_class ovr --max_iter 423"
"884  --dataset cifar10 --job_id 1540458 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.6353 --lr_solver liblinear --multi_class ovr --lr_penalty l2 --lr_dual True"
"901  --dataset cifar10 --job_id 1540458 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.0571 --lr_solver lbfgs --multi_class ovr --max_iter 515"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
