#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-3
#SBATCH --job-name=cifar10-3f5k15m-irace-val
#SBATCH --output=validation/cifar10-3f5k15m-irace-1585123-1585126/cifar10-3f5k15m-irace-1585124-val-%A-%a

CONFIGS=("928  --dataset cifar10 --job_id 1585124 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 88 --scaling True --algorithm LogisticRegression --lr_C -2.9807 --lr_solver lbfgs --multi_class ovr --max_iter 411"
"924  --dataset cifar10 --job_id 1585124 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 83 --scaling True --algorithm LogisticRegression --lr_C -3.0696 --lr_solver lbfgs --multi_class ovr --max_iter 176"
"939  --dataset cifar10 --job_id 1585124 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 97 --scaling True --algorithm LogisticRegression --lr_C -3.2466 --lr_solver lbfgs --multi_class ovr --max_iter 465"
"954  --dataset cifar10 --job_id 1585124 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 97 --scaling True --algorithm LogisticRegression --lr_C -3.6128 --lr_solver lbfgs --multi_class ovr --max_iter 465"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
