#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-3f5k15m-irace-val
#SBATCH --output=validation/cifar10-3f5k15m-irace-1585123-1585126/cifar10-3f5k15m-irace-1585125-val-%A-%a

CONFIGS=("934  --dataset cifar10 --job_id 1585125 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 37 --scaling True --algorithm SVM --C -3.0748 --kernel linear"
"581  --dataset cifar10 --job_id 1585125 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0229 --whiten False --svd_solver full --scaling True --algorithm SVM --C -2.1002 --kernel linear"
"919  --dataset cifar10 --job_id 1585125 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 33 --scaling True --algorithm SVM --C -2.602 --kernel linear"
"867  --dataset cifar10 --job_id 1585125 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 37 --scaling True --algorithm SVM --C -1.7356 --kernel linear"
"746  --dataset cifar10 --job_id 1585125 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling True --algorithm SVM --C -2.0588 --kernel linear"
"943  --dataset cifar10 --job_id 1585125 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 63 --scaling True --algorithm SVM --C -3.3458 --kernel linear"
"935  --dataset cifar10 --job_id 1585125 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 38 --scaling True --algorithm SVM --C -2.8833 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
