#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-5
#SBATCH --job-name=cifar10-3f5k15m-irace-val
#SBATCH --output=validation/cifar10-3f5k15m-irace-1585123-1585126/cifar10-3f5k15m-irace-1585126-val-%A-%a

CONFIGS=("639  --dataset cifar10 --job_id 1585126 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0203 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 83 --scaling False --algorithm KNeighbors --n_neighbors 47 --weights distance"
"615  --dataset cifar10 --job_id 1585126 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0541 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 62 --scaling False --algorithm KNeighbors --n_neighbors 32 --weights distance"
"622  --dataset cifar10 --job_id 1585126 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 50 --scaling False --algorithm SVM --C -3.6545 --kernel linear"
"433  --dataset cifar10 --job_id 1585126 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.5608 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 26 --scaling False --algorithm KNeighbors --n_neighbors 36 --weights distance"
"503  --dataset cifar10 --job_id 1585126 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 99 --weights distance"
"949  --dataset cifar10 --job_id 1585126 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0214 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 86 --scaling False --algorithm KNeighbors --n_neighbors 9 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
