#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-5
#SBATCH --job-name=cifar10-3f2k30m-irace-val
#SBATCH --output=validation/cifar10-3f2k30m-irace-1585128-1585132/cifar10-3f2k30m-irace-1585132-val-%A-%a

CONFIGS=("233  --dataset cifar10 --job_id 1585132 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 91 --scaling True --algorithm SVM --C 2.2543 --kernel rbf --gamma -3.524"
"87   --dataset cifar10 --job_id 1585132 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 52 --scaling True --algorithm SVM --C 2.4014 --kernel rbf --gamma -4.4368"
"186  --dataset cifar10 --job_id 1585132 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling True --algorithm SVM --C -2.7552 --kernel rbf --gamma -2.8333"
"310  --dataset cifar10 --job_id 1585132 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 83 --scaling True --algorithm SVM --C 3.0128 --kernel rbf --gamma -3.3027"
"335  --dataset cifar10 --job_id 1585132 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling True --algorithm SVM --C 0.124 --kernel rbf --gamma -2.5186"
"353  --dataset cifar10 --job_id 1585132 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 88 --scaling True --algorithm SVM --C 0.8633 --kernel rbf --gamma -3.788"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
