#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=cifar10-3f2k30m-irace-val
#SBATCH --output=validation/cifar10-3f2k30m-irace-1585128-1585132/cifar10-3f2k30m-irace-1585130-val-%A-%a

CONFIGS=("255  --dataset cifar10 --job_id 1585130 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0317 --whiten True --svd_solver auto --scaling True --algorithm LogisticRegression --lr_C -2.1606 --lr_solver sag --multi_class multinomial --max_iter 440"
"182  --dataset cifar10 --job_id 1585130 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0372 --whiten True --svd_solver auto --scaling True --algorithm LogisticRegression --lr_C -2.8266 --lr_solver sag --multi_class multinomial --max_iter 550"
"331  --dataset cifar10 --job_id 1585130 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0193 --whiten True --svd_solver auto --scaling True --algorithm LogisticRegression --lr_C -1.8621 --lr_solver sag --multi_class multinomial --max_iter 105"
"351  --dataset cifar10 --job_id 1585130 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0302 --whiten True --svd_solver auto --scaling True --algorithm LogisticRegression --lr_C -3.4786 --lr_solver sag --multi_class multinomial --max_iter 393"
"358  --dataset cifar10 --job_id 1585130 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0102 --whiten True --svd_solver auto --scaling True --algorithm LogisticRegression --lr_C -2.0885 --lr_solver sag --multi_class multinomial --max_iter 495"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
