#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-3f2k30m-irace-val
#SBATCH --output=validation/cifar10-3f2k30m-irace-1585128-1585132/cifar10-3f2k30m-irace-1585129-val-%A-%a

CONFIGS=("282  --dataset cifar10 --job_id 1585129 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2875 --lr_solver lbfgs --multi_class ovr --max_iter 204"
"360  --dataset cifar10 --job_id 1585129 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2334 --lr_solver lbfgs --multi_class ovr --max_iter 490"
"344  --dataset cifar10 --job_id 1585129 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2626 --lr_solver lbfgs --multi_class ovr --max_iter 207"
"245  --dataset cifar10 --job_id 1585129 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2926 --lr_solver lbfgs --multi_class ovr --max_iter 731"
"306  --dataset cifar10 --job_id 1585129 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3322 --lr_solver lbfgs --multi_class ovr --max_iter 498"
"301  --dataset cifar10 --job_id 1585129 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3733 --lr_solver lbfgs --multi_class ovr --max_iter 195"
"318  --dataset cifar10 --job_id 1585129 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3491 --lr_solver lbfgs --multi_class ovr --max_iter 682"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
