#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=svhn-1f2k20m-irace-val
#SBATCH --output=validation/svhn-1f2k20m-irace-1585238-1585242/svhn-1f2k20m-irace-1585242-val-%A-%a

CONFIGS=("272  --dataset svhn --job_id 1585242 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0611 --whiten False --svd_solver full --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"326  --dataset svhn --job_id 1585242 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.055 --whiten False --svd_solver full --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 14 --weights distance"
"339  --dataset svhn --job_id 1585242 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.106 --whiten False --svd_solver full --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 9 --weights distance"
"355  --dataset svhn --job_id 1585242 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0288 --whiten False --svd_solver full --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"360  --dataset svhn --job_id 1585242 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.043 --whiten False --svd_solver full --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 7 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
