#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-2
#SBATCH --job-name=svhn-1f2k10m-irace-val
#SBATCH --output=validation/svhn-1f2k10m-irace-1585228-1585232/svhn-1f2k10m-irace-1585231-val-%A-%a

CONFIGS=("299  --dataset svhn --job_id 1585231 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0169 --whiten True --svd_solver arpack --scaling False --algorithm KNeighbors --n_neighbors 28 --weights uniform"
"311  --dataset svhn --job_id 1585231 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0142 --whiten False --svd_solver auto --scaling True --algorithm KNeighbors --n_neighbors 44 --weights uniform"
"330  --dataset svhn --job_id 1585231 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0161 --whiten True --svd_solver arpack --scaling False --algorithm KNeighbors --n_neighbors 14 --weights uniform"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
