#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-1f2k10m-irace-val
#SBATCH --output=validation/svhn-1f2k10m-irace-1585228-1585232/svhn-1f2k10m-irace-1585228-val-%A-%a

CONFIGS=("278  --dataset svhn --job_id 1585228 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 23 --scaling False --algorithm KNeighbors --n_neighbors 11 --weights uniform"
"258  --dataset svhn --job_id 1585228 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 23 --scaling False --algorithm KNeighbors --n_neighbors 7 --weights uniform"
"271  --dataset svhn --job_id 1585228 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling False --algorithm KNeighbors --n_neighbors 11 --weights uniform"
"295  --dataset svhn --job_id 1585228 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling False --algorithm KNeighbors --n_neighbors 10 --weights uniform"
"323  --dataset svhn --job_id 1585228 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 24 --scaling False --algorithm KNeighbors --n_neighbors 5 --weights uniform"
"338  --dataset svhn --job_id 1585228 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 15 --scaling False --algorithm KNeighbors --n_neighbors 10 --weights uniform"
"349  --dataset svhn --job_id 1585228 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 52 --scaling False --algorithm KNeighbors --n_neighbors 14 --weights uniform"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
