#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-1f2k10m-irace-val
#SBATCH --output=validation/svhn-1f2k10m-irace-1585228-1585232/svhn-1f2k10m-irace-1585232-val-%A-%a

CONFIGS=("285  --dataset svhn --job_id 1585232 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 10 --scaling True --algorithm LogisticRegression --lr_C -1.2639 --lr_solver newton-cg --multi_class ovr --max_iter 404"
"311  --dataset svhn --job_id 1585232 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 33 --scaling True --algorithm LogisticRegression --lr_C -3.032 --lr_solver newton-cg --multi_class multinomial --max_iter 633"
"319  --dataset svhn --job_id 1585232 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 12 --scaling True --algorithm LogisticRegression --lr_C -1.7574 --lr_solver newton-cg --multi_class ovr --max_iter 245"
"188  --dataset svhn --job_id 1585232 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 39 --scaling True --algorithm LogisticRegression --lr_C -1.2952 --lr_solver newton-cg --multi_class ovr --max_iter 282"
"203  --dataset svhn --job_id 1585232 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 15 --scaling True --algorithm LogisticRegression --lr_C -2.4605 --lr_solver newton-cg --multi_class ovr --max_iter 202"
"178  --dataset svhn --job_id 1585232 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0481 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 49 --scaling True --algorithm AdaBoost --ab_estimators 66 --ab_learning_rate 0.0711"
"355  --dataset svhn --job_id 1585232 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0419 --whiten False --svd_solver full --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 24 --scaling True --algorithm AdaBoost --ab_estimators 113 --ab_learning_rate 0.2977"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
