#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k20m-irace-val
#SBATCH --output=validation/cifar100-1f2k20m-irace-1554139-1554143/cifar100-1f2k20m-irace-1554143-val-%A-%a

CONFIGS=("250  --dataset cifar100 --job_id 1554143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 3.0293 --kernel linear"
"251  --dataset cifar100 --job_id 1554143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 3.0064 --kernel linear"
"252  --dataset cifar100 --job_id 1554143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -0.302 --kernel linear"
"253  --dataset cifar100 --job_id 1554143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 4.1203 --kernel linear"
"258  --dataset cifar100 --job_id 1554143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -2.5299 --kernel linear"
"259  --dataset cifar100 --job_id 1554143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -1.0083 --kernel linear"
"261  --dataset cifar100 --job_id 1554143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 1.7712 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
