#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=cifar100-1f2k20m-irace-val
#SBATCH --output=validation/cifar100-1f2k20m-irace-1554139-1554143/cifar100-1f2k20m-irace-1554140-val-%A-%a

CONFIGS=("355  --dataset cifar100 --job_id 1554140 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 83 --scaling False --algorithm SVM --C 0.5208 --kernel rbf --gamma -3.8014"
"185  --dataset cifar100 --job_id 1554140 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 79 --scaling False --algorithm SVM --C 4.2667 --kernel rbf --gamma -3.553"
"305  --dataset cifar100 --job_id 1554140 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 70 --scaling False --algorithm SVM --C 0.8317 --kernel rbf --gamma -3.0602"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
