#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k20m-irace-val
#SBATCH --output=validation/cifar100-1f2k20m-irace-1554139-1554143/cifar100-1f2k20m-irace-1554139-val-%A-%a

CONFIGS=("124  --dataset cifar100 --job_id 1554139 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -3.2241 --kernel linear"
"343  --dataset cifar100 --job_id 1554139 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1591 --kernel linear"
"239  --dataset cifar100 --job_id 1554139 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.5348 --kernel linear"
"341  --dataset cifar100 --job_id 1554139 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.0932 --kernel linear"
"342  --dataset cifar100 --job_id 1554139 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.0326 --kernel linear"
"344  --dataset cifar100 --job_id 1554139 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.8178 --kernel linear"
"345  --dataset cifar100 --job_id 1554139 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -0.7489 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
