#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k20m-irace-val
#SBATCH --output=validation/cifar100-1f2k20m-irace-1554139-1554143/cifar100-1f2k20m-irace-1554141-val-%A-%a

CONFIGS=("312  --dataset cifar100 --job_id 1554141 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 1.533 --hidden_layers 1 --neurons1 405 --activation relu"
"196  --dataset cifar100 --job_id 1554141 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 0.073 --hidden_layers 1 --neurons1 170 --activation relu"
"241  --dataset cifar100 --job_id 1554141 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 1.1795 --hidden_layers 1 --neurons1 123 --activation relu"
"224  --dataset cifar100 --job_id 1554141 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha -1.9629 --hidden_layers 1 --neurons1 143 --activation relu"
"351  --dataset cifar100 --job_id 1554141 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 0.027 --hidden_layers 1 --neurons1 180 --activation relu"
"346  --dataset cifar100 --job_id 1554141 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha -0.4588 --hidden_layers 1 --neurons1 156 --activation relu"
"356  --dataset cifar100 --job_id 1554141 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 2.0726 --hidden_layers 1 --neurons1 213 --activation relu"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
