#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k20m-irace-val
#SBATCH --output=validation/cifar100-1f2k20m-irace-1554139-1554143/cifar100-1f2k20m-irace-1554142-val-%A-%a

CONFIGS=("149  --dataset cifar100 --job_id 1554142 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 2.8652 --kernel linear"
"152  --dataset cifar100 --job_id 1554142 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -3.7441 --kernel linear"
"153  --dataset cifar100 --job_id 1554142 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 0.1008 --kernel linear"
"159  --dataset cifar100 --job_id 1554142 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -3.3959 --kernel linear"
"163  --dataset cifar100 --job_id 1554142 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 0.1232 --kernel linear"
"164  --dataset cifar100 --job_id 1554142 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -2.251 --kernel linear"
"165  --dataset cifar100 --job_id 1554142 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -3.8585 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
