#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1545515-1545519/fashion-mnist-1f5k10m-irace-1545517-val-%A-%a

CONFIGS=("762  --dataset fashion-mnist --job_id 1545517 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -2.3636 --kernel poly --degree 1 --gamma -3.7219"
"674  --dataset fashion-mnist --job_id 1545517 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -2.3847 --kernel poly --degree 1 --gamma -3.5104"
"573  --dataset fashion-mnist --job_id 1545517 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -1.1156 --kernel poly --degree 1 --gamma -4.8372"
"604  --dataset fashion-mnist --job_id 1545517 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.2235 --kernel linear"
"900  --dataset fashion-mnist --job_id 1545517 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1446 --kernel linear"
"755  --dataset fashion-mnist --job_id 1545517 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.2219 --kernel linear"
"887  --dataset fashion-mnist --job_id 1545517 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -1.1713 --kernel poly --degree 1 --gamma -4.9778"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
