#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1545515-1545519/fashion-mnist-1f5k10m-irace-1545515-val-%A-%a

CONFIGS=("537  --dataset fashion-mnist --job_id 1545515 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 86 --scaling False --algorithm SVM --C 1.7521 --kernel rbf --gamma -2.6651"
"616  --dataset fashion-mnist --job_id 1545515 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 77 --scaling False --algorithm SVM --C 0.338 --kernel rbf --gamma -2.4624"
"821  --dataset fashion-mnist --job_id 1545515 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 83 --scaling False --algorithm SVM --C 1.7052 --kernel rbf --gamma -2.843"
"611  --dataset fashion-mnist --job_id 1545515 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 84 --scaling False --algorithm SVM --C 0.265 --kernel rbf --gamma -2.5255"
"251  --dataset fashion-mnist --job_id 1545515 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 72 --scaling False --algorithm SVM --C 2.0646 --kernel rbf --gamma -4.4918"
"365  --dataset fashion-mnist --job_id 1545515 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -0.3991 --kernel poly --degree 1 --gamma -1.9316"
"371  --dataset fashion-mnist --job_id 1545515 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -1.9077 --kernel poly --degree 3 --gamma -0.7058"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
