#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1545515-1545519/fashion-mnist-1f5k10m-irace-1545519-val-%A-%a

CONFIGS=("620  --dataset fashion-mnist --job_id 1545519 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -1.178 --kernel poly --degree 2 --gamma -1.8183"
"880  --dataset fashion-mnist --job_id 1545519 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -3.8714 --kernel poly --degree 2 --gamma -0.391"
"546  --dataset fashion-mnist --job_id 1545519 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.3364 --kernel poly --degree 2 --gamma -1.0961"
"562  --dataset fashion-mnist --job_id 1545519 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.7085 --kernel poly --degree 2 --gamma -0.8501"
"563  --dataset fashion-mnist --job_id 1545519 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 3.9383 --kernel poly --degree 2 --gamma -4.1957"
"943  --dataset fashion-mnist --job_id 1545519 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 3.8209 --kernel poly --degree 2 --gamma -4.3036"
"920  --dataset fashion-mnist --job_id 1545519 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.4475 --kernel poly --degree 2 --gamma -0.7624"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
