#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1545515-1545519/fashion-mnist-1f5k10m-irace-1545516-val-%A-%a

CONFIGS=("919  --dataset fashion-mnist --job_id 1545516 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 1.6397 --hidden_layers 1 --neurons1 99 --activation tanh"
"932  --dataset fashion-mnist --job_id 1545516 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 1.6371 --hidden_layers 1 --neurons1 67 --activation tanh"
"926  --dataset fashion-mnist --job_id 1545516 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha -0.1581 --hidden_layers 1 --neurons1 156 --activation tanh"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
