#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-4
#SBATCH --job-name=fashion-mnist-3f5k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f5k15m-irace-1545500-1545504/fashion-mnist-3f5k15m-irace-1545501-val-%A-%a

CONFIGS=("509  --dataset fashion-mnist --job_id 1545501 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.8407 --kernel rbf --gamma -3.1628"
"721  --dataset fashion-mnist --job_id 1545501 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.8858 --kernel rbf --gamma -3.0673"
"806  --dataset fashion-mnist --job_id 1545501 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.7711 --kernel rbf --gamma -3.2848"
"918  --dataset fashion-mnist --job_id 1545501 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.1061 --kernel rbf --gamma -3.0697"
"949  --dataset fashion-mnist --job_id 1545501 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.8744 --kernel rbf --gamma -3.1386"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
