#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=fashion-mnist-3f5k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f5k15m-irace-1545500-1545504/fashion-mnist-3f5k15m-irace-1545502-val-%A-%a

CONFIGS=("751  --dataset fashion-mnist --job_id 1545502 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.5981 --kernel rbf --gamma -3.0303"
"771  --dataset fashion-mnist --job_id 1545502 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.8413 --kernel rbf --gamma -3.0834"
"729  --dataset fashion-mnist --job_id 1545502 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.8663 --kernel rbf --gamma -3.2268"
"572  --dataset fashion-mnist --job_id 1545502 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 2.6629 --kernel rbf --gamma -2.9596"
"450  --dataset fashion-mnist --job_id 1545502 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 3.097 --kernel rbf --gamma -2.8076"
"574  --dataset fashion-mnist --job_id 1545502 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 2.4671 --kernel rbf --gamma -2.8514"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
