#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=fashion-mnist-3f5k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f5k15m-irace-1545500-1545504/fashion-mnist-3f5k15m-irace-1545504-val-%A-%a

CONFIGS=("802  --dataset fashion-mnist --job_id 1545504 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.873 --kernel rbf --gamma -3.3313"
"864  --dataset fashion-mnist --job_id 1545504 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.6273 --kernel rbf --gamma -3.2737"
"839  --dataset fashion-mnist --job_id 1545504 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.1784 --kernel rbf --gamma -3.3664"
"376  --dataset fashion-mnist --job_id 1545504 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 3.5285 --kernel rbf --gamma -2.9203"
"587  --dataset fashion-mnist --job_id 1545504 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.9777 --kernel rbf --gamma -3.7035"
"654  --dataset fashion-mnist --job_id 1545504 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.5952 --kernel rbf --gamma -4.0837"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
