#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f5k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f5k15m-irace-1585339-1585343/fashion-mnist-3f5k15m-irace-1585343-val-%A-%a

CONFIGS=("922  --dataset fashion-mnist --job_id 1585343 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.9135 --lr_solver newton-cg --multi_class multinomial --max_iter 629"
"871  --dataset fashion-mnist --job_id 1585343 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.9388 --lr_solver newton-cg --multi_class multinomial --max_iter 473"
"384  --dataset fashion-mnist --job_id 1585343 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.9859 --lr_solver newton-cg --multi_class multinomial --max_iter 841"
"412  --dataset fashion-mnist --job_id 1585343 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.9743 --lr_solver newton-cg --multi_class multinomial --max_iter 683"
"924  --dataset fashion-mnist --job_id 1585343 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -2.0058 --lr_solver newton-cg --multi_class multinomial --max_iter 730"
"929  --dataset fashion-mnist --job_id 1585343 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.9998 --lr_solver newton-cg --multi_class multinomial --max_iter 898"
"945  --dataset fashion-mnist --job_id 1585343 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.5782 --lr_solver newton-cg --multi_class multinomial --max_iter 937"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
