#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f5k15m-irace-val
#SBATCH --output=validation/fashion-mnist-3f5k15m-irace-1585339-1585343/fashion-mnist-3f5k15m-irace-1585340-val-%A-%a

CONFIGS=("525  --dataset fashion-mnist --job_id 1585340 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 80 --scaling False --algorithm SVM --C 4.3752 --kernel rbf --gamma -2.7381"
"895  --dataset fashion-mnist --job_id 1585340 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 91 --scaling False --algorithm SVM --C 0.5741 --kernel rbf --gamma -2.9376"
"677  --dataset fashion-mnist --job_id 1585340 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 85 --scaling False --algorithm SVM --C 3.9812 --kernel rbf --gamma -2.6651"
"818  --dataset fashion-mnist --job_id 1585340 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 95 --scaling False --algorithm SVM --C 0.7945 --kernel rbf --gamma -2.9843"
"779  --dataset fashion-mnist --job_id 1585340 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 88 --scaling False --algorithm SVM --C 4.7999 --kernel rbf --gamma -2.6901"
"673  --dataset fashion-mnist --job_id 1585340 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 88 --scaling False --algorithm SVM --C 3.9763 --kernel rbf --gamma -2.7065"
"811  --dataset fashion-mnist --job_id 1585340 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 73 --scaling False --algorithm SVM --C 3.6485 --kernel rbf --gamma -2.5257"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
