#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-4
#SBATCH --job-name=cifar10-3f2k15m-irace-val
#SBATCH --output=validation/cifar10-3f2k15m-irace-1540436-1540440/cifar10-3f2k15m-irace-1540437-val-%A-%a

CONFIGS=("242  --dataset cifar10 --job_id 1540437 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 91 --scaling False --algorithm RandomForest --rf_estimators 197 --criterion_classification gini --max_features 0.3716 --max_depth value --max_depth_value 10 --min_samples_leaf 0.0123"
"328  --dataset cifar10 --job_id 1540437 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 52 --scaling False --algorithm RandomForest --rf_estimators 401 --criterion_classification gini --max_features 0.1076 --max_depth value --max_depth_value 24 --min_samples_leaf 0.0145"
"196  --dataset cifar10 --job_id 1540437 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 42 --scaling False --algorithm RandomForest --rf_estimators 276 --criterion_classification gini --max_features 0.0657 --max_depth value --max_depth_value 16 --min_samples_leaf 0.0119"
"182  --dataset cifar10 --job_id 1540437 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm RandomForest --rf_estimators 790 --criterion_classification gini --max_features 0.0642 --max_depth value --max_depth_value 25 --min_samples_leaf 0.0258"
"345  --dataset cifar10 --job_id 1540437 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm RandomForest --rf_estimators 770 --criterion_classification gini --max_features 0.1822 --max_depth value --max_depth_value 17 --min_samples_leaf 0.0107"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
