#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-3f2k15m-irace-val
#SBATCH --output=validation/cifar10-3f2k15m-irace-1540436-1540440/cifar10-3f2k15m-irace-1540436-val-%A-%a

CONFIGS=("239  --dataset cifar10 --job_id 1540436 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.6946 --lr_solver lbfgs --multi_class ovr --max_iter 571"
"237  --dataset cifar10 --job_id 1540436 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -2.7142 --lr_solver lbfgs --multi_class ovr --max_iter 347"
"243  --dataset cifar10 --job_id 1540436 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.7722 --lr_solver lbfgs --multi_class ovr --max_iter 802"
"368  --dataset cifar10 --job_id 1540436 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.3788 --lr_solver lbfgs --multi_class ovr --max_iter 633"
"367  --dataset cifar10 --job_id 1540436 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4554 --lr_solver lbfgs --multi_class ovr --max_iter 546"
"357  --dataset cifar10 --job_id 1540436 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4267 --lr_solver lbfgs --multi_class ovr --max_iter 946"
"345  --dataset cifar10 --job_id 1540436 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.703 --lr_solver lbfgs --multi_class ovr --max_iter 691"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
