#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-3f2k15m-irace-val
#SBATCH --output=validation/cifar10-3f2k15m-irace-1540436-1540440/cifar10-3f2k15m-irace-1540440-val-%A-%a

CONFIGS=("247  --dataset cifar10 --job_id 1540440 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 9 --weights distance"
"331  --dataset cifar10 --job_id 1540440 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 9 --weights distance"
"333  --dataset cifar10 --job_id 1540440 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 11 --weights distance"
"256  --dataset cifar10 --job_id 1540440 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 6 --weights distance"
"296  --dataset cifar10 --job_id 1540440 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"342  --dataset cifar10 --job_id 1540440 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 20 --weights distance"
"318  --dataset cifar10 --job_id 1540440 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 19 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
