#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1586328-1586332/cifar100-3f2k15m-irace-1586330-val-%A-%a

CONFIGS=("356  --dataset cifar100 --job_id 1586330 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 98 --scaling False --algorithm SVM --C -0.3108 --kernel linear"
"353  --dataset cifar100 --job_id 1586330 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 85 --scaling False --algorithm SVM --C -1.1186 --kernel linear"
"313  --dataset cifar100 --job_id 1586330 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 80 --scaling False --algorithm SVM --C 1.392 --kernel linear"
"350  --dataset cifar100 --job_id 1586330 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 80 --scaling False --algorithm SVM --C 1.2809 --kernel linear"
"321  --dataset cifar100 --job_id 1586330 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 76 --scaling False --algorithm SVM --C -2.1063 --kernel linear"
"362  --dataset cifar100 --job_id 1586330 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 90 --scaling False --algorithm SVM --C 0.514 --kernel linear"
"368  --dataset cifar100 --job_id 1586330 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 92 --scaling False --algorithm SVM --C -2.1002 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
