#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-3
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1586328-1586332/cifar100-3f2k15m-irace-1586331-val-%A-%a

CONFIGS=("356  --dataset cifar100 --job_id 1586331 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling True --extraction PCA --ext_components 0.1904 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 9 --scaling False --algorithm KNeighbors --n_neighbors 28 --weights uniform"
"343  --dataset cifar100 --job_id 1586331 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling True --extraction PCA --ext_components 0.0477 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 14 --scaling False --algorithm KNeighbors --n_neighbors 29 --weights uniform"
"350  --dataset cifar100 --job_id 1586331 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling True --extraction PCA --ext_components 0.1411 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 7 --scaling False --algorithm KNeighbors --n_neighbors 37 --weights uniform"
"357  --dataset cifar100 --job_id 1586331 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling True --extraction PCA --ext_components 0.0448 --whiten False --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 15 --scaling False --algorithm KNeighbors --n_neighbors 22 --weights uniform"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
