#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1586328-1586332/cifar100-3f2k15m-irace-1586328-val-%A-%a

CONFIGS=("215  --dataset cifar100 --job_id 1586328 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 62 --scaling False --algorithm SVM --C -2.5824 --kernel poly --degree 1 --gamma 0.7337"
"268  --dataset cifar100 --job_id 1586328 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 58 --scaling False --algorithm SVM --C -2.3714 --kernel poly --degree 1 --gamma -0.5467"
"267  --dataset cifar100 --job_id 1586328 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 57 --scaling False --algorithm SVM --C -1.8856 --kernel poly --degree 1 --gamma -1.0404"
"330  --dataset cifar100 --job_id 1586328 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 88 --scaling False --algorithm SVM --C -1.3835 --kernel poly --degree 1 --gamma -1.9201"
"284  --dataset cifar100 --job_id 1586328 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 70 --scaling False --algorithm SVM --C -0.3965 --kernel poly --degree 1 --gamma -2.1738"
"262  --dataset cifar100 --job_id 1586328 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 52 --scaling False --algorithm SVM --C -0.3087 --kernel poly --degree 1 --gamma -2.1577"
"261  --dataset cifar100 --job_id 1586328 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 44 --scaling False --algorithm SVM --C -2.8516 --kernel poly --degree 1 --gamma 0.3169"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
