#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-3
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1586328-1586332/cifar100-3f2k15m-irace-1586329-val-%A-%a

CONFIGS=("188  --dataset cifar100 --job_id 1586329 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.016 --whiten True --svd_solver randomized --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 51 --scaling False --algorithm SVM --C -1.626 --kernel sigmoid --gamma -3.7286"
"351  --dataset cifar100 --job_id 1586329 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.2064 --whiten True --svd_solver randomized --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 25 --scaling False --algorithm SVM --C 0.5599 --kernel sigmoid --gamma -2.4575"
"359  --dataset cifar100 --job_id 1586329 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.1803 --whiten True --svd_solver randomized --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 19 --scaling False --algorithm SVM --C 0.2562 --kernel sigmoid --gamma -2.9067"
"367  --dataset cifar100 --job_id 1586329 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.1426 --whiten True --svd_solver randomized --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 12 --scaling False --algorithm SVM --C -2.6027 --kernel sigmoid --gamma -3.4651"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
