#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-5
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1585359-1585363/fashion-mnist-1f2k20m-irace-1585360-val-%A-%a

CONFIGS=("257  --dataset fashion-mnist --job_id 1585360 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.7778 --kernel rbf --gamma -2.6798"
"272  --dataset fashion-mnist --job_id 1585360 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 1.6017 --kernel rbf --gamma -2.2613"
"321  --dataset fashion-mnist --job_id 1585360 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.6036 --kernel rbf --gamma -2.4566"
"333  --dataset fashion-mnist --job_id 1585360 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 1.994 --kernel rbf --gamma -2.325"
"325  --dataset fashion-mnist --job_id 1585360 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 1.8421 --kernel rbf --gamma -2.1645"
"358  --dataset fashion-mnist --job_id 1585360 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 3.4107 --kernel rbf --gamma -2.4723"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
