#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-3
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1585359-1585363/fashion-mnist-1f2k20m-irace-1585361-val-%A-%a

CONFIGS=("168  --dataset fashion-mnist --job_id 1585361 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 73 --scaling True --algorithm SVM --C 3.3016 --kernel rbf --gamma -2.8131"
"317  --dataset fashion-mnist --job_id 1585361 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 63 --scaling True --algorithm SVM --C 3.7588 --kernel rbf --gamma -2.6191"
"303  --dataset fashion-mnist --job_id 1585361 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 78 --scaling True --algorithm SVM --C 3.503 --kernel rbf --gamma -2.9306"
"365  --dataset fashion-mnist --job_id 1585361 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 85 --scaling True --algorithm SVM --C 3.2948 --kernel rbf --gamma -2.4691"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
