#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1585359-1585363/fashion-mnist-1f2k20m-irace-1585362-val-%A-%a

CONFIGS=("295  --dataset fashion-mnist --job_id 1585362 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.723 --hidden_layers 1 --neurons1 315 --activation relu"
"298  --dataset fashion-mnist --job_id 1585362 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.4121 --hidden_layers 1 --neurons1 361 --activation relu"
"70   --dataset fashion-mnist --job_id 1585362 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.6594 --hidden_layers 1 --neurons1 117 --activation relu"
"314  --dataset fashion-mnist --job_id 1585362 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 0.8243 --hidden_layers 1 --neurons1 208 --activation relu"
"285  --dataset fashion-mnist --job_id 1585362 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.0594 --hidden_layers 1 --neurons1 201 --activation relu"
"215  --dataset fashion-mnist --job_id 1585362 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.3426 --hidden_layers 1 --neurons1 78 --activation relu"
"246  --dataset fashion-mnist --job_id 1585362 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.2694 --hidden_layers 1 --neurons1 219 --activation relu"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
