#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1585359-1585363/fashion-mnist-1f2k20m-irace-1585363-val-%A-%a

CONFIGS=("356  --dataset fashion-mnist --job_id 1585363 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.493 --hidden_layers 1 --neurons1 328 --activation relu"
"278  --dataset fashion-mnist --job_id 1585363 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.7356 --hidden_layers 1 --neurons1 74 --activation relu"
"315  --dataset fashion-mnist --job_id 1585363 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.5917 --hidden_layers 1 --neurons1 250 --activation relu"
"340  --dataset fashion-mnist --job_id 1585363 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.0692 --hidden_layers 1 --neurons1 267 --activation relu"
"363  --dataset fashion-mnist --job_id 1585363 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 0.948 --hidden_layers 1 --neurons1 381 --activation relu"
"328  --dataset fashion-mnist --job_id 1585363 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 0.6747 --hidden_layers 1 --neurons1 239 --activation relu"
"254  --dataset fashion-mnist --job_id 1585363 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.617 --hidden_layers 1 --neurons1 72 --activation relu"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
