#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1585359-1585363/fashion-mnist-1f2k20m-irace-1585359-val-%A-%a

CONFIGS=("327  --dataset fashion-mnist --job_id 1585359 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1962 --kernel linear"
"277  --dataset fashion-mnist --job_id 1585359 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.3395 --kernel linear"
"202  --dataset fashion-mnist --job_id 1585359 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.2144 --kernel linear"
"257  --dataset fashion-mnist --job_id 1585359 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1237 --kernel linear"
"305  --dataset fashion-mnist --job_id 1585359 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.281 --kernel linear"
"272  --dataset fashion-mnist --job_id 1585359 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.3644 --kernel linear"
"262  --dataset fashion-mnist --job_id 1585359 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.3919 --kernel linear"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
