#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=cifar10-1f2k20m-irace-val
#SBATCH --output=validation/cifar10-1f2k20m-irace-1540461-1540465/cifar10-1f2k20m-irace-1540465-val-%A-%a

CONFIGS=("191  --dataset cifar10 --job_id 1540465 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 74 --scaling True --algorithm SVM --C 0.8713 --kernel rbf --gamma -4.1548"
"345  --dataset cifar10 --job_id 1540465 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 67 --scaling True --algorithm SVM --C 1.0959 --kernel rbf --gamma -3.8472"
"356  --dataset cifar10 --job_id 1540465 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 83 --scaling True --algorithm SVM --C 2.4604 --kernel rbf --gamma -3.5771"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
