#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-3
#SBATCH --job-name=cifar10-1f2k20m-irace-val
#SBATCH --output=validation/cifar10-1f2k20m-irace-1540461-1540465/cifar10-1f2k20m-irace-1540462-val-%A-%a

CONFIGS=("315  --dataset cifar10 --job_id 1540462 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.1123 --whiten False --svd_solver arpack --scaling False --algorithm LogisticRegression --lr_C -3.4626 --lr_solver lbfgs --multi_class multinomial --max_iter 364"
"337  --dataset cifar10 --job_id 1540462 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.0564 --whiten False --svd_solver arpack --scaling False --algorithm LogisticRegression --lr_C -3.4398 --lr_solver lbfgs --multi_class multinomial --max_iter 452"
"359  --dataset cifar10 --job_id 1540462 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.3073 --whiten False --svd_solver arpack --scaling False --algorithm LogisticRegression --lr_C -3.2487 --lr_solver lbfgs --multi_class multinomial --max_iter 429"
"369  --dataset cifar10 --job_id 1540462 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling True --extraction PCA --ext_components 0.3954 --whiten False --svd_solver arpack --scaling False --algorithm LogisticRegression --lr_C -3.395 --lr_solver lbfgs --multi_class multinomial --max_iter 567"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
