#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1545520-1545524/fashion-mnist-1f2k20m-irace-1545523-val-%A-%a

CONFIGS=("298  --dataset fashion-mnist --job_id 1545523 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 80 --scaling True --algorithm SVM --C 1.0238 --kernel rbf --gamma -2.5075"
"106  --dataset fashion-mnist --job_id 1545523 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 90 --scaling True --algorithm SVM --C 2.4973 --kernel rbf --gamma -2.6569"
"254  --dataset fashion-mnist --job_id 1545523 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 93 --scaling True --algorithm SVM --C 3.6288 --kernel rbf --gamma -2.8407"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
