#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-3
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1545520-1545524/fashion-mnist-1f2k20m-irace-1545521-val-%A-%a

CONFIGS=("339  --dataset fashion-mnist --job_id 1545521 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 1.4129 --hidden_layers 1 --neurons1 261 --activation relu"
"345  --dataset fashion-mnist --job_id 1545521 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 1.4027 --hidden_layers 1 --neurons1 462 --activation relu"
"314  --dataset fashion-mnist --job_id 1545521 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 0.7929 --hidden_layers 1 --neurons1 469 --activation relu"
"342  --dataset fashion-mnist --job_id 1545521 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm MLP --solver lbfgs --alpha 1.7038 --hidden_layers 1 --neurons1 236 --activation relu"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
