#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1545520-1545524/fashion-mnist-1f2k20m-irace-1545520-val-%A-%a

CONFIGS=("319  --dataset fashion-mnist --job_id 1545520 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm MLP --solver lbfgs --alpha -0.6796 --hidden_layers 1 --neurons1 176 --activation logistic"
"323  --dataset fashion-mnist --job_id 1545520 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm MLP --solver lbfgs --alpha -0.7255 --hidden_layers 1 --neurons1 194 --activation logistic"
"324  --dataset fashion-mnist --job_id 1545520 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm MLP --solver lbfgs --alpha -0.93 --hidden_layers 1 --neurons1 137 --activation logistic"
"303  --dataset fashion-mnist --job_id 1545520 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm MLP --solver lbfgs --alpha 0.8198 --hidden_layers 1 --neurons1 169 --activation logistic"
"297  --dataset fashion-mnist --job_id 1545520 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm MLP --solver lbfgs --alpha 0.6767 --hidden_layers 1 --neurons1 127 --activation logistic"
"327  --dataset fashion-mnist --job_id 1545520 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm MLP --solver lbfgs --alpha -0.3854 --hidden_layers 1 --neurons1 133 --activation logistic"
"360  --dataset fashion-mnist --job_id 1545520 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm MLP --solver lbfgs --alpha -0.0923 --hidden_layers 1 --neurons1 194 --activation logistic"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
