#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k20m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k20m-irace-1545520-1545524/fashion-mnist-1f2k20m-irace-1545524-val-%A-%a

CONFIGS=("262  --dataset fashion-mnist --job_id 1545524 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.8925 --lr_solver lbfgs --multi_class multinomial --max_iter 589"
"256  --dataset fashion-mnist --job_id 1545524 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.8179 --lr_solver newton-cg --multi_class multinomial --max_iter 119"
"201  --dataset fashion-mnist --job_id 1545524 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.9419 --lr_solver lbfgs --multi_class multinomial --max_iter 257"
"329  --dataset fashion-mnist --job_id 1545524 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7354 --lr_solver newton-cg --multi_class multinomial --max_iter 114"
"351  --dataset fashion-mnist --job_id 1545524 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7361 --lr_solver lbfgs --multi_class multinomial --max_iter 640"
"301  --dataset fashion-mnist --job_id 1545524 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7971 --lr_solver newton-cg --multi_class multinomial --max_iter 322"
"275  --dataset fashion-mnist --job_id 1545524 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.7391 --lr_solver newton-cg --multi_class multinomial --max_iter 455"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
