#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-0
#SBATCH --job-name=cifar10-3f2k30m-irace-val
#SBATCH --output=validation/cifar10-3f2k30m-irace-1540446-1540450/cifar10-3f2k30m-irace-1540448-val-%A-%a

CONFIGS=("358  --dataset cifar10 --job_id 1540448 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm RandomForest --rf_estimators 394 --criterion_classification gini --max_features 0.469 --max_depth none --min_samples_leaf 0.0135"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
