#!/bin/bash
#SBATCH --time=0-8:40
#SBATCH --job-name=valiskl
#SBATCH --cpus-per-task=1
#SBATCH --output=validation-isklearn-weekly-natal-crimes_%j.out
#SBATCH --array=0-5

CONFIGS=("311  --dataset natal-crimes --task regression --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction FastICA --ext_components 0.6263 --ica_algorithm parallel --ica_fun logcosh --scaling True --algorithm LinearRegression" 
"357  --dataset natal-crimes --task regression --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction FastICA --ext_components 0.6652 --ica_algorithm parallel --ica_fun exp --scaling False --algorithm LinearRegression" 
"131  --dataset natal-crimes --task regression --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction FastICA --ext_components 0.6479 --ica_algorithm deflation --ica_fun cube --scaling True --algorithm LinearRegression" 
"197  --dataset natal-crimes --task regression --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction FastICA --ext_components 0.6513 --ica_algorithm parallel --ica_fun exp --scaling False --algorithm LinearRegression" 
"116  --dataset natal-crimes --task regression --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction FastICA --ext_components 0.632 --ica_algorithm parallel --ica_fun cube --scaling False --algorithm LinearRegression" 
"189  --dataset natal-crimes --task regression --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction FastICA --ext_components 0.6491 --ica_algorithm parallel --ica_fun cube --scaling True --algorithm LinearRegression" 
)

srun python /home/addaraujo2/isklearn/natal-crimes/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
