#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1585138-1585142/cifar10-1f5k10m-irace-1585142-val-%A-%a

CONFIGS=("676  --dataset cifar10 --job_id 1585142 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.326 --lr_solver newton-cg --multi_class multinomial --max_iter 313"
"839  --dataset cifar10 --job_id 1585142 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.324 --lr_solver lbfgs --multi_class multinomial --max_iter 356"
"869  --dataset cifar10 --job_id 1585142 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3137 --lr_solver lbfgs --multi_class multinomial --max_iter 342"
"747  --dataset cifar10 --job_id 1585142 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2681 --lr_solver lbfgs --multi_class multinomial --max_iter 897"
"750  --dataset cifar10 --job_id 1585142 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4023 --lr_solver lbfgs --multi_class multinomial --max_iter 311"
"523  --dataset cifar10 --job_id 1585142 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4527 --lr_solver lbfgs --multi_class multinomial --max_iter 286"
"836  --dataset cifar10 --job_id 1585142 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2622 --lr_solver newton-cg --multi_class multinomial --max_iter 431"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
