#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1585138-1585142/cifar10-1f5k10m-irace-1585139-val-%A-%a

CONFIGS=("723  --dataset cifar10 --job_id 1585139 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3742 --lr_solver newton-cg --multi_class multinomial --max_iter 215"
"886  --dataset cifar10 --job_id 1585139 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3764 --lr_solver newton-cg --multi_class multinomial --max_iter 128"
"841  --dataset cifar10 --job_id 1585139 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4498 --lr_solver newton-cg --multi_class multinomial --max_iter 125"
"631  --dataset cifar10 --job_id 1585139 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4186 --lr_solver lbfgs --multi_class multinomial --max_iter 214"
"586  --dataset cifar10 --job_id 1585139 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3706 --lr_solver newton-cg --multi_class multinomial --max_iter 164"
"906  --dataset cifar10 --job_id 1585139 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4464 --lr_solver newton-cg --multi_class multinomial --max_iter 342"
"892  --dataset cifar10 --job_id 1585139 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4683 --lr_solver newton-cg --multi_class multinomial --max_iter 316"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
