#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1585138-1585142/cifar10-1f5k10m-irace-1585141-val-%A-%a

CONFIGS=("892  --dataset cifar10 --job_id 1585141 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.1163 --lr_solver lbfgs --multi_class multinomial --max_iter 424"
"906  --dataset cifar10 --job_id 1585141 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.1206 --lr_solver lbfgs --multi_class multinomial --max_iter 872"
"927  --dataset cifar10 --job_id 1585141 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3273 --lr_solver lbfgs --multi_class multinomial --max_iter 239"
"809  --dataset cifar10 --job_id 1585141 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.0896 --lr_solver lbfgs --multi_class multinomial --max_iter 424"
"833  --dataset cifar10 --job_id 1585141 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3795 --lr_solver lbfgs --multi_class ovr --max_iter 281"
"873  --dataset cifar10 --job_id 1585141 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.1145 --lr_solver lbfgs --multi_class multinomial --max_iter 751"
"769  --dataset cifar10 --job_id 1585141 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.0822 --lr_solver lbfgs --multi_class multinomial --max_iter 325"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
