#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1585138-1585142/cifar10-1f5k10m-irace-1585138-val-%A-%a

CONFIGS=("249  --dataset cifar10 --job_id 1585138 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction FastICA --ext_components 0.0232 --ica_algorithm parallel --ica_fun logcosh --scaling False --algorithm LogisticRegression --lr_C -0.2527 --lr_solver lbfgs --multi_class ovr --max_iter 355"
"570  --dataset cifar10 --job_id 1585138 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction FastICA --ext_components 0.0107 --ica_algorithm parallel --ica_fun logcosh --scaling True --algorithm LogisticRegression --lr_C -2.1857 --lr_solver lbfgs --multi_class ovr --max_iter 295"
"915  --dataset cifar10 --job_id 1585138 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction FastICA --ext_components 0.0347 --ica_algorithm parallel --ica_fun logcosh --scaling False --algorithm LogisticRegression --lr_C 0.6937 --lr_solver lbfgs --multi_class ovr --max_iter 314"
"791  --dataset cifar10 --job_id 1585138 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction FastICA --ext_components 0.055 --ica_algorithm parallel --ica_fun logcosh --scaling False --algorithm LogisticRegression --lr_C -0.4571 --lr_solver lbfgs --multi_class ovr --max_iter 635"
"955  --dataset cifar10 --job_id 1585138 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction FastICA --ext_components 0.0262 --ica_algorithm parallel --ica_fun logcosh --scaling True --algorithm LogisticRegression --lr_C -3.5764 --lr_solver lbfgs --multi_class ovr --max_iter 425"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
