#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f5k10m-irace-val
#SBATCH --output=validation/cifar10-1f5k10m-irace-1585138-1585142/cifar10-1f5k10m-irace-1585140-val-%A-%a

CONFIGS=("806  --dataset cifar10 --job_id 1585140 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4081 --lr_solver lbfgs --multi_class multinomial --max_iter 721"
"734  --dataset cifar10 --job_id 1585140 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4048 --lr_solver lbfgs --multi_class multinomial --max_iter 277"
"707  --dataset cifar10 --job_id 1585140 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2672 --lr_solver lbfgs --multi_class multinomial --max_iter 609"
"602  --dataset cifar10 --job_id 1585140 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.4211 --lr_solver lbfgs --multi_class multinomial --max_iter 536"
"861  --dataset cifar10 --job_id 1585140 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.473 --lr_solver lbfgs --multi_class multinomial --max_iter 401"
"821  --dataset cifar10 --job_id 1585140 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.261 --lr_solver lbfgs --multi_class multinomial --max_iter 250"
"711  --dataset cifar10 --job_id 1585140 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3862 --lr_solver lbfgs --multi_class multinomial --max_iter 631"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
