#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1554114-1554118/cifar100-3f2k15m-irace-1554118-val-%A-%a

CONFIGS=("325  --dataset cifar100 --job_id 1554118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 70 --scaling False --algorithm KNeighbors --n_neighbors 12 --weights distance"
"224  --dataset cifar100 --job_id 1554118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 73 --scaling False --algorithm KNeighbors --n_neighbors 15 --weights distance"
"163  --dataset cifar100 --job_id 1554118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 74 --scaling False --algorithm KNeighbors --n_neighbors 16 --weights distance"
"318  --dataset cifar100 --job_id 1554118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 51 --scaling False --algorithm KNeighbors --n_neighbors 18 --weights distance"
"328  --dataset cifar100 --job_id 1554118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 56 --scaling False --algorithm KNeighbors --n_neighbors 18 --weights distance"
"261  --dataset cifar100 --job_id 1554118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 59 --scaling False --algorithm KNeighbors --n_neighbors 17 --weights distance"
"165  --dataset cifar100 --job_id 1554118 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 54 --scaling False --algorithm KNeighbors --n_neighbors 28 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
