#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1554114-1554118/cifar100-3f2k15m-irace-1554114-val-%A-%a

CONFIGS=("304  --dataset cifar100 --job_id 1554114 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 58 --scaling False --algorithm KNeighbors --n_neighbors 22 --weights distance"
"346  --dataset cifar100 --job_id 1554114 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 67 --scaling False --algorithm KNeighbors --n_neighbors 19 --weights distance"
"344  --dataset cifar100 --job_id 1554114 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 72 --scaling False --algorithm KNeighbors --n_neighbors 17 --weights distance"
"302  --dataset cifar100 --job_id 1554114 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 69 --scaling False --algorithm KNeighbors --n_neighbors 28 --weights distance"
"318  --dataset cifar100 --job_id 1554114 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 59 --scaling False --algorithm KNeighbors --n_neighbors 13 --weights distance"
"339  --dataset cifar100 --job_id 1554114 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 46 --scaling False --algorithm KNeighbors --n_neighbors 9 --weights distance"
"358  --dataset cifar100 --job_id 1554114 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 76 --scaling False --algorithm KNeighbors --n_neighbors 14 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
