#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-4
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1554114-1554118/cifar100-3f2k15m-irace-1554115-val-%A-%a

CONFIGS=("323  --dataset cifar100 --job_id 1554115 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 24 --weights distance"
"315  --dataset cifar100 --job_id 1554115 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 14 --weights distance"
"354  --dataset cifar100 --job_id 1554115 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 11 --weights distance"
"360  --dataset cifar100 --job_id 1554115 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 9 --weights distance"
"356  --dataset cifar100 --job_id 1554115 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 13 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
