#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k15m-irace-val
#SBATCH --output=validation/cifar100-3f2k15m-irace-1554114-1554118/cifar100-3f2k15m-irace-1554117-val-%A-%a

CONFIGS=("262  --dataset cifar100 --job_id 1554117 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0184 --whiten False --svd_solver arpack --scaling True --algorithm SVM --C -1.3837 --kernel linear"
"228  --dataset cifar100 --job_id 1554117 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0254 --whiten False --svd_solver arpack --scaling True --algorithm SVM --C 0.8357 --kernel linear"
"227  --dataset cifar100 --job_id 1554117 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling True --algorithm SVM --C 0.2314 --kernel sigmoid --gamma -3.0945"
"40   --dataset cifar100 --job_id 1554117 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0349 --whiten False --svd_solver arpack --scaling True --algorithm SVM --C -2.4085 --kernel linear"
"124  --dataset cifar100 --job_id 1554117 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 14 --scaling True --algorithm SVM --C -3.2458 --kernel sigmoid --gamma -2.819"
"50   --dataset cifar100 --job_id 1554117 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 39 --scaling True --algorithm RandomForest --rf_estimators 17 --criterion_classification entropy --max_features 0.0685 --max_depth value --max_depth_value 2 --min_samples_leaf 0.1792"
"82   --dataset cifar100 --job_id 1554117 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0447 --whiten True --svd_solver auto --scaling True --algorithm SVM --C 0.387 --kernel sigmoid --gamma -0.2831"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
