#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-3f5k15m-irace-val
#SBATCH --output=validation/cifar10-3f5k15m-irace-1585333/cifar10-3f5k15m-irace-1585333-val-%A-%a

CONFIGS=("615  --dataset cifar10 --job_id 1585333 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 42 --scaling True --algorithm SVM --C 4.4341 --kernel rbf --gamma -2.4398"
"419  --dataset cifar10 --job_id 1585333 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 62 --scaling True --algorithm KNeighbors --n_neighbors 23 --weights distance"
"443  --dataset cifar10 --job_id 1585333 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 34 --weights uniform"
"303  --dataset cifar10 --job_id 1585333 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 30 --scaling True --algorithm KNeighbors --n_neighbors 40 --weights distance"
"237  --dataset cifar10 --job_id 1585333 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 36 --scaling False --algorithm KNeighbors --n_neighbors 30 --weights uniform"
"192  --dataset cifar10 --job_id 1585333 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling False --algorithm KNeighbors --n_neighbors 89 --weights uniform"
"43   --dataset cifar10 --job_id 1585333 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 21 --scaling True --algorithm DecisionTree --criterion_classification entropy --max_features 0.6737 --max_depth value --max_depth_value 18 --min_samples_leaf 0.1204"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
