#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f5k15m-irace-val
#SBATCH --output=validation/cifar100-3f5k15m-irace-1554119-1554123/cifar100-3f5k15m-irace-1554120-val-%A-%a

CONFIGS=("592  --dataset cifar100 --job_id 1554120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.1518 --max_depth value --max_depth_value 35 --min_samples_leaf 0.0102"
"911  --dataset cifar100 --job_id 1554120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.369 --max_depth value --max_depth_value 46 --min_samples_leaf 0.0145"
"696  --dataset cifar100 --job_id 1554120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.345 --max_depth value --max_depth_value 28 --min_samples_leaf 0.0132"
"529  --dataset cifar100 --job_id 1554120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.3526 --max_depth value --max_depth_value 32 --min_samples_leaf 0.0115"
"682  --dataset cifar100 --job_id 1554120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.2796 --max_depth value --max_depth_value 36 --min_samples_leaf 0.0174"
"848  --dataset cifar100 --job_id 1554120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.2081 --max_depth value --max_depth_value 12 --min_samples_leaf 0.0149"
"540  --dataset cifar100 --job_id 1554120 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.0839 --max_depth value --max_depth_value 42 --min_samples_leaf 0.0185"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
