#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f5k15m-irace-val
#SBATCH --output=validation/cifar100-3f5k15m-irace-1554119-1554123/cifar100-3f5k15m-irace-1554123-val-%A-%a

CONFIGS=("756  --dataset cifar100 --job_id 1554123 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.7779 --max_depth none --max_depth_value 36 --min_samples_leaf 0.0129"
"641  --dataset cifar100 --job_id 1554123 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.8403 --max_depth none --max_depth_value 34 --min_samples_leaf 0.0137"
"721  --dataset cifar100 --job_id 1554123 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.3803 --max_depth none --max_depth_value 6 --min_samples_leaf 0.0142"
"645  --dataset cifar100 --job_id 1554123 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.4394 --max_depth none --max_depth_value 14 --min_samples_leaf 0.0119"
"746  --dataset cifar100 --job_id 1554123 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.7718 --max_depth none --max_depth_value 41 --min_samples_leaf 0.0153"
"899  --dataset cifar100 --job_id 1554123 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.5361 --max_depth none --max_depth_value 6 --min_samples_leaf 0.0101"
"754  --dataset cifar100 --job_id 1554123 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.6494 --max_depth none --max_depth_value 45 --min_samples_leaf 0.0195"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
