#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f5k15m-irace-val
#SBATCH --output=validation/cifar100-3f5k15m-irace-1554119-1554123/cifar100-3f5k15m-irace-1554119-val-%A-%a

CONFIGS=("795  --dataset cifar100 --job_id 1554119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -3.1031 --kernel linear"
"797  --dataset cifar100 --job_id 1554119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -2.9348 --kernel linear"
"802  --dataset cifar100 --job_id 1554119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -1.3618 --kernel linear"
"803  --dataset cifar100 --job_id 1554119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -3.5367 --kernel linear"
"806  --dataset cifar100 --job_id 1554119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -3.6289 --kernel linear"
"809  --dataset cifar100 --job_id 1554119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C -2.0465 --kernel linear"
"810  --dataset cifar100 --job_id 1554119 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm SVM --C 0.2334 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
