#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f5k15m-irace-val
#SBATCH --output=validation/cifar100-3f5k15m-irace-1554119-1554123/cifar100-3f5k15m-irace-1554122-val-%A-%a

CONFIGS=("939  --dataset cifar100 --job_id 1554122 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0825 --whiten False --svd_solver auto --scaling False --algorithm SVM --C -2.729 --kernel linear"
"790  --dataset cifar100 --job_id 1554122 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.1069 --whiten False --svd_solver auto --scaling False --algorithm SVM --C -2.0688 --kernel linear"
"944  --dataset cifar100 --job_id 1554122 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.044 --whiten False --svd_solver auto --scaling False --algorithm SVM --C -3.449 --kernel linear"
"619  --dataset cifar100 --job_id 1554122 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0906 --whiten False --svd_solver auto --scaling False --algorithm SVM --C -3.4623 --kernel linear"
"907  --dataset cifar100 --job_id 1554122 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0895 --whiten False --svd_solver auto --scaling False --algorithm SVM --C -0.1952 --kernel linear"
"905  --dataset cifar100 --job_id 1554122 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0339 --whiten False --svd_solver auto --scaling False --algorithm SVM --C -2.0112 --kernel linear"
"859  --dataset cifar100 --job_id 1554122 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0241 --whiten False --svd_solver auto --scaling False --algorithm SVM --C -2.2399 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
