#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-5
#SBATCH --job-name=cifar100-3f5k15m-irace-val
#SBATCH --output=validation/cifar100-3f5k15m-irace-1586333-1586337/cifar100-3f5k15m-irace-1586337-val-%A-%a

CONFIGS=("710  --dataset cifar100 --job_id 1586337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.023 --whiten True --svd_solver randomized --scaling True --algorithm SVM --C -1.6896 --kernel linear"
"807  --dataset cifar100 --job_id 1586337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0152 --whiten True --svd_solver randomized --scaling True --algorithm SVM --C -2.7709 --kernel linear"
"838  --dataset cifar100 --job_id 1586337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0151 --whiten True --svd_solver randomized --scaling True --algorithm SVM --C 0.1912 --kernel linear"
"873  --dataset cifar100 --job_id 1586337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0283 --whiten True --svd_solver randomized --scaling True --algorithm SVM --C 3.7451 --kernel linear"
"900  --dataset cifar100 --job_id 1586337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0111 --whiten True --svd_solver randomized --scaling True --algorithm SVM --C -3.4538 --kernel linear"
"908  --dataset cifar100 --job_id 1586337 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0231 --whiten True --svd_solver randomized --scaling True --algorithm SVM --C 3.1158 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
