#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-1
#SBATCH --job-name=cifar100-3f5k15m-irace-val
#SBATCH --output=validation/cifar100-3f5k15m-irace-1586333-1586337/cifar100-3f5k15m-irace-1586336-val-%A-%a

CONFIGS=("943  --dataset cifar100 --job_id 1586336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"927  --dataset cifar100 --job_id 1586336 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 11 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
