#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-3f2k15m-irace-val
#SBATCH --output=validation/svhn-3f2k15m-irace-1554194-1554198/svhn-3f2k15m-irace-1554198-val-%A-%a

CONFIGS=("199  --dataset svhn --job_id 1554198 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0114 --whiten False --svd_solver randomized --scaling True --algorithm KNeighbors --n_neighbors 3 --weights uniform"
"186  --dataset svhn --job_id 1554198 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 18 --scaling True --algorithm KNeighbors --n_neighbors 15 --weights uniform"
"163  --dataset svhn --job_id 1554198 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm KNeighbors --n_neighbors 5 --weights uniform"
"85   --dataset svhn --job_id 1554198 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm KNeighbors --n_neighbors 39 --weights uniform"
"33   --dataset svhn --job_id 1554198 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0516 --whiten False --svd_solver arpack --scaling True --algorithm KNeighbors --n_neighbors 33 --weights uniform"
"146  --dataset svhn --job_id 1554198 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 1 --scaling True --algorithm KNeighbors --n_neighbors 76 --weights uniform"
"102  --dataset svhn --job_id 1554198 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.9622 --max_depth value --max_depth_value 39 --min_samples_leaf 0.3046"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
