#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=svhn-3f2k15m-irace-val
#SBATCH --output=validation/svhn-3f2k15m-irace-1554194-1554198/svhn-3f2k15m-irace-1554196-val-%A-%a

CONFIGS=("181  --dataset svhn --job_id 1554196 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.5354 --max_depth value --max_depth_value 10 --min_samples_leaf 0.0616"
"162  --dataset svhn --job_id 1554196 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 21 --scaling False --algorithm LogisticRegression --lr_C -3.0518 --lr_solver lbfgs --multi_class multinomial --max_iter 402"
"275  --dataset svhn --job_id 1554196 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.5378 --max_depth value --max_depth_value 15 --min_samples_leaf 0.017"
"271  --dataset svhn --job_id 1554196 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.035 --max_depth value --max_depth_value 40 --min_samples_leaf 0.02"
"352  --dataset svhn --job_id 1554196 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.4184 --max_depth value --max_depth_value 28 --min_samples_leaf 0.0203"
"351  --dataset svhn --job_id 1554196 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.4892 --max_depth value --max_depth_value 12 --min_samples_leaf 0.0205"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
