#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=svhn-3f2k15m-irace-val
#SBATCH --output=validation/svhn-3f2k15m-irace-1554194-1554198/svhn-3f2k15m-irace-1554197-val-%A-%a

CONFIGS=("209  --dataset svhn --job_id 1554197 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 13 --weights distance"
"221  --dataset svhn --job_id 1554197 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 14 --weights distance"
"168  --dataset svhn --job_id 1554197 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 15 --weights distance"
"71   --dataset svhn --job_id 1554197 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 13 --scaling False --algorithm KNeighbors --n_neighbors 9 --weights distance"
"130  --dataset svhn --job_id 1554197 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 39 --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"363  --dataset svhn --job_id 1554197 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 15 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
