#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-3f2k15m-irace-val
#SBATCH --output=validation/svhn-3f2k15m-irace-1554194-1554198/svhn-3f2k15m-irace-1554194-val-%A-%a

CONFIGS=("231  --dataset svhn --job_id 1554194 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.5056 --max_depth value --max_depth_value 26 --min_samples_leaf 0.0105"
"280  --dataset svhn --job_id 1554194 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.3673 --max_depth value --max_depth_value 18 --min_samples_leaf 0.0147"
"295  --dataset svhn --job_id 1554194 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.7084 --max_depth value --max_depth_value 28 --min_samples_leaf 0.0202"
"310  --dataset svhn --job_id 1554194 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.5738 --max_depth value --max_depth_value 47 --min_samples_leaf 0.0221"
"254  --dataset svhn --job_id 1554194 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.3914 --max_depth value --max_depth_value 36 --min_samples_leaf 0.0229"
"252  --dataset svhn --job_id 1554194 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.7702 --max_depth value --max_depth_value 22 --min_samples_leaf 0.026"
"260  --dataset svhn --job_id 1554194 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.8325 --max_depth value --max_depth_value 39 --min_samples_leaf 0.0346"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
