#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-1f5k10m-irace-val
#SBATCH --output=validation/svhn-1f5k10m-irace-1585233-1585237/svhn-1f5k10m-irace-1585233-val-%A-%a

CONFIGS=("865  --dataset svhn --job_id 1585233 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0207 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 40 --scaling False --algorithm KNeighbors --n_neighbors 26 --weights distance"
"545  --dataset svhn --job_id 1585233 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0258 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 36 --scaling False --algorithm KNeighbors --n_neighbors 26 --weights distance"
"683  --dataset svhn --job_id 1585233 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0163 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 35 --scaling False --algorithm KNeighbors --n_neighbors 38 --weights distance"
"842  --dataset svhn --job_id 1585233 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0329 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 18 --scaling False --algorithm KNeighbors --n_neighbors 34 --weights distance"
"823  --dataset svhn --job_id 1585233 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0135 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 43 --scaling False --algorithm KNeighbors --n_neighbors 45 --weights distance"
"893  --dataset svhn --job_id 1585233 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0409 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling False --algorithm KNeighbors --n_neighbors 13 --weights distance"
"941  --dataset svhn --job_id 1585233 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0451 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 18 --scaling False --algorithm KNeighbors --n_neighbors 23 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
