#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-1f5k10m-irace-val
#SBATCH --output=validation/svhn-1f5k10m-irace-1585233-1585237/svhn-1f5k10m-irace-1585236-val-%A-%a

CONFIGS=("824  --dataset svhn --job_id 1585236 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 45 --scaling True --algorithm SVM --C -0.9259 --kernel poly --degree 2 --gamma -1.8314"
"638  --dataset svhn --job_id 1585236 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 36 --scaling True --algorithm SVM --C 0.922 --kernel poly --degree 2 --gamma -2.7947"
"877  --dataset svhn --job_id 1585236 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 45 --scaling True --algorithm SVM --C -1.4975 --kernel poly --degree 2 --gamma -1.3123"
"682  --dataset svhn --job_id 1585236 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 48 --scaling True --algorithm SVM --C 4.4017 --kernel poly --degree 2 --gamma -4.2404"
"713  --dataset svhn --job_id 1585236 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 38 --scaling True --algorithm SVM --C 1.2295 --kernel poly --degree 2 --gamma 0.7413"
"606  --dataset svhn --job_id 1585236 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 44 --scaling True --algorithm SVM --C 0.3063 --kernel poly --degree 2 --gamma -1.4472"
"598  --dataset svhn --job_id 1585236 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 35 --scaling True --algorithm SVM --C 4.7019 --kernel poly --degree 2 --gamma -1.0671"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
