#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=cifar10-1f2k20m-irace-val
#SBATCH --output=validation/cifar10-1f2k20m-irace-1585143-1585147/cifar10-1f2k20m-irace-1585144-val-%A-%a

CONFIGS=("291  --dataset cifar10 --job_id 1585144 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 1.8828 --kernel rbf --gamma -3.0548"
"230  --dataset cifar10 --job_id 1585144 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 4.2484 --kernel rbf --gamma -2.8556"
"289  --dataset cifar10 --job_id 1585144 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 2.109 --kernel rbf --gamma -2.8302"
"317  --dataset cifar10 --job_id 1585144 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 0.3544 --kernel rbf --gamma -3.249"
"359  --dataset cifar10 --job_id 1585144 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 1.4287 --kernel rbf --gamma -2.9819"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
