#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k20m-irace-val
#SBATCH --output=validation/cifar10-1f2k20m-irace-1585143-1585147/cifar10-1f2k20m-irace-1585146-val-%A-%a

CONFIGS=("289  --dataset cifar10 --job_id 1585146 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -2.8555 --lr_solver newton-cg --multi_class multinomial --max_iter 818"
"315  --dataset cifar10 --job_id 1585146 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -2.8869 --lr_solver newton-cg --multi_class multinomial --max_iter 822"
"316  --dataset cifar10 --job_id 1585146 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -3.198 --lr_solver newton-cg --multi_class multinomial --max_iter 215"
"252  --dataset cifar10 --job_id 1585146 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -3.2135 --lr_solver newton-cg --multi_class multinomial --max_iter 347"
"351  --dataset cifar10 --job_id 1585146 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -3.0647 --lr_solver newton-cg --multi_class multinomial --max_iter 615"
"368  --dataset cifar10 --job_id 1585146 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -2.7496 --lr_solver newton-cg --multi_class multinomial --max_iter 287"
"361  --dataset cifar10 --job_id 1585146 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -3.0109 --lr_solver newton-cg --multi_class multinomial --max_iter 688"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
