#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k20m-irace-val
#SBATCH --output=validation/cifar10-1f2k20m-irace-1585143-1585147/cifar10-1f2k20m-irace-1585143-val-%A-%a

CONFIGS=("312  --dataset cifar10 --job_id 1585143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.6511 --lr_solver newton-cg --multi_class ovr --max_iter 275"
"197  --dataset cifar10 --job_id 1585143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 96 --scaling True --algorithm LogisticRegression --lr_C -2.7835 --lr_solver newton-cg --multi_class ovr --max_iter 528"
"361  --dataset cifar10 --job_id 1585143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.0906 --lr_solver newton-cg --multi_class ovr --max_iter 321"
"362  --dataset cifar10 --job_id 1585143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -2.9033 --lr_solver newton-cg --multi_class ovr --max_iter 626"
"354  --dataset cifar10 --job_id 1585143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 84 --scaling True --algorithm LogisticRegression --lr_C -2.8839 --lr_solver newton-cg --multi_class ovr --max_iter 452"
"355  --dataset cifar10 --job_id 1585143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -2.7064 --lr_solver newton-cg --multi_class ovr --max_iter 513"
"356  --dataset cifar10 --job_id 1585143 --cutoff 20 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.913 --lr_solver newton-cg --multi_class ovr --max_iter 494"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
