#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=fashion-mnist-3f2k30m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k30m-irace-1585344-1585348/fashion-mnist-3f2k30m-irace-1585344-val-%A-%a

CONFIGS=("87   --dataset fashion-mnist --job_id 1585344 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha -4.6265 --hidden_layers 3 --neurons1 177 --neurons2 91 --neurons3 92 --activation relu"
"55   --dataset fashion-mnist --job_id 1585344 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm SVM --C -0.566 --kernel linear"
"37   --dataset fashion-mnist --job_id 1585344 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm KNeighbors --n_neighbors 4 --weights uniform"
"287  --dataset fashion-mnist --job_id 1585344 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1448 --kernel linear"
"322  --dataset fashion-mnist --job_id 1585344 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha -1.6183 --hidden_layers 2 --neurons1 235 --neurons2 89 --activation relu"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
