#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=fashion-mnist-3f2k30m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k30m-irace-1585344-1585348/fashion-mnist-3f2k30m-irace-1585348-val-%A-%a

CONFIGS=("36   --dataset fashion-mnist --job_id 1585348 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1626 --kernel poly --degree 2 --gamma -1.352"
"316  --dataset fashion-mnist --job_id 1585348 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.7782 --kernel poly --degree 2 --gamma -1.0911"
"333  --dataset fashion-mnist --job_id 1585348 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.3602 --kernel poly --degree 2 --gamma -2.9369"
"364  --dataset fashion-mnist --job_id 1585348 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -0.8475 --kernel poly --degree 2 --gamma -1.9564"
"379  --dataset fashion-mnist --job_id 1585348 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -0.4839 --kernel poly --degree 2 --gamma -2.2989"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
