#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k30m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k30m-irace-1585344-1585348/fashion-mnist-3f2k30m-irace-1585346-val-%A-%a

CONFIGS=("277  --dataset fashion-mnist --job_id 1585346 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1802 --kernel linear"
"201  --dataset fashion-mnist --job_id 1585346 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.2224 --kernel linear"
"315  --dataset fashion-mnist --job_id 1585346 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.9854 --kernel linear"
"314  --dataset fashion-mnist --job_id 1585346 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.5395 --kernel linear"
"360  --dataset fashion-mnist --job_id 1585346 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.3334 --kernel linear"
"359  --dataset fashion-mnist --job_id 1585346 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1284 --kernel linear"
"367  --dataset fashion-mnist --job_id 1585346 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.4412 --kernel linear"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
