#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-1
#SBATCH --job-name=svhn-3f2k15m-irace-val
#SBATCH --output=validation/svhn-3f2k15m-irace-1585213-1585217/svhn-3f2k15m-irace-1585215-val-%A-%a

CONFIGS=("328  --dataset svhn --job_id 1585215 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 51 --weights distance"
"355  --dataset svhn --job_id 1585215 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm RandomForest --rf_estimators 716 --criterion_classification gini --max_features 0.5889 --max_depth value --max_depth_value 44 --min_samples_leaf 0.3707"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
