#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-2
#SBATCH --job-name=svhn-3f2k15m-irace-val
#SBATCH --output=validation/svhn-3f2k15m-irace-1585213-1585217/svhn-3f2k15m-irace-1585214-val-%A-%a

CONFIGS=("326  --dataset svhn --job_id 1585214 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 24 --scaling False --algorithm KNeighbors --n_neighbors 8 --weights distance"
"345  --dataset svhn --job_id 1585214 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 16 --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"261  --dataset svhn --job_id 1585214 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 27 --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
