#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-3
#SBATCH --job-name=svhn-3f2k15m-irace-val
#SBATCH --output=validation/svhn-3f2k15m-irace-1585213-1585217/svhn-3f2k15m-irace-1585217-val-%A-%a

CONFIGS=("295  --dataset svhn --job_id 1585217 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.7817 --max_depth value --max_depth_value 29 --min_samples_leaf 0.0105"
"361  --dataset svhn --job_id 1585217 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.8347 --max_depth value --max_depth_value 44 --min_samples_leaf 0.0138"
"343  --dataset svhn --job_id 1585217 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.8415 --max_depth value --max_depth_value 21 --min_samples_leaf 0.0189"
"319  --dataset svhn --job_id 1585217 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.4843 --max_depth value --max_depth_value 23 --min_samples_leaf 0.0285"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
