#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f5k10m-irace-val
#SBATCH --output=validation/cifar100-1f5k10m-irace-1554134-1554138/cifar100-1f5k10m-irace-1554134-val-%A-%a

CONFIGS=("926  --dataset cifar100 --job_id 1554134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0214 --whiten True --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 25 --scaling False --algorithm KNeighbors --n_neighbors 24 --weights distance"
"733  --dataset cifar100 --job_id 1554134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0348 --whiten True --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 10 --scaling False --algorithm KNeighbors --n_neighbors 33 --weights distance"
"631  --dataset cifar100 --job_id 1554134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0457 --whiten True --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 8 --scaling False --algorithm KNeighbors --n_neighbors 66 --weights distance"
"706  --dataset cifar100 --job_id 1554134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0169 --whiten True --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 21 --scaling False --algorithm KNeighbors --n_neighbors 49 --weights distance"
"583  --dataset cifar100 --job_id 1554134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.111 --whiten True --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 3 --scaling False --algorithm KNeighbors --n_neighbors 46 --weights distance"
"641  --dataset cifar100 --job_id 1554134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.1381 --whiten True --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 4 --scaling False --algorithm KNeighbors --n_neighbors 24 --weights distance"
"526  --dataset cifar100 --job_id 1554134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0307 --whiten True --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 17 --scaling False --algorithm KNeighbors --n_neighbors 69 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
