#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1585354-1585358/fashion-mnist-1f5k10m-irace-1585355-val-%A-%a

CONFIGS=("862  --dataset fashion-mnist --job_id 1585355 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.4504 --kernel rbf --gamma -2.9778"
"561  --dataset fashion-mnist --job_id 1585355 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.4641 --kernel rbf --gamma -2.91"
"540  --dataset fashion-mnist --job_id 1585355 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.413 --kernel rbf --gamma -2.9618"
"886  --dataset fashion-mnist --job_id 1585355 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.3217 --kernel rbf --gamma -3.6133"
"893  --dataset fashion-mnist --job_id 1585355 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.8882 --kernel rbf --gamma -3.6083"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
