#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1585354-1585358/fashion-mnist-1f5k10m-irace-1585354-val-%A-%a

CONFIGS=("528  --dataset fashion-mnist --job_id 1585354 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.0598 --kernel rbf --gamma -3.0239"
"918  --dataset fashion-mnist --job_id 1585354 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.1798 --kernel rbf --gamma -3.4187"
"787  --dataset fashion-mnist --job_id 1585354 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.4432 --kernel rbf --gamma -3.0003"
"592  --dataset fashion-mnist --job_id 1585354 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.7701 --kernel rbf --gamma -2.8357"
"912  --dataset fashion-mnist --job_id 1585354 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.149 --kernel rbf --gamma -3.2921"
"589  --dataset fashion-mnist --job_id 1585354 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 0.3514 --kernel rbf --gamma -2.8677"
"726  --dataset fashion-mnist --job_id 1585354 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C 1.0582 --kernel rbf --gamma -3.5214"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
