#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1585354-1585358/fashion-mnist-1f5k10m-irace-1585356-val-%A-%a

CONFIGS=("519  --dataset fashion-mnist --job_id 1585356 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha -0.0182 --hidden_layers 1 --neurons1 124 --activation tanh"
"810  --dataset fashion-mnist --job_id 1585356 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.2768 --hidden_layers 1 --neurons1 153 --activation tanh"
"902  --dataset fashion-mnist --job_id 1585356 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.618 --hidden_layers 1 --neurons1 251 --activation tanh"
"799  --dataset fashion-mnist --job_id 1585356 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha -0.1 --hidden_layers 1 --neurons1 141 --activation tanh"
"816  --dataset fashion-mnist --job_id 1585356 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 1.2675 --hidden_layers 1 --neurons1 174 --activation tanh"
"898  --dataset fashion-mnist --job_id 1585356 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm MLP --solver lbfgs --alpha 0.7164 --hidden_layers 1 --neurons1 86 --activation tanh"
"553  --dataset fashion-mnist --job_id 1585356 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1843 --kernel linear"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
