#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1585354-1585358/fashion-mnist-1f5k10m-irace-1585358-val-%A-%a

CONFIGS=("886  --dataset fashion-mnist --job_id 1585358 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.705 --kernel rbf --gamma -2.8429"
"888  --dataset fashion-mnist --job_id 1585358 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.6853 --kernel rbf --gamma -2.4884"
"945  --dataset fashion-mnist --job_id 1585358 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.6747 --kernel rbf --gamma -2.5449"
"659  --dataset fashion-mnist --job_id 1585358 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.8923 --kernel rbf --gamma -2.4981"
"844  --dataset fashion-mnist --job_id 1585358 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 0.5726 --kernel rbf --gamma -2.3952"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
