#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f5k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f5k10m-irace-1585354-1585358/fashion-mnist-1f5k10m-irace-1585357-val-%A-%a

CONFIGS=("818  --dataset fashion-mnist --job_id 1585357 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.1421 --kernel poly --degree 2 --gamma -1.2309"
"662  --dataset fashion-mnist --job_id 1585357 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.8005 --kernel poly --degree 2 --gamma -0.9722"
"782  --dataset fashion-mnist --job_id 1585357 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -0.5701 --kernel poly --degree 2 --gamma -2.0151"
"837  --dataset fashion-mnist --job_id 1585357 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -1.2422 --kernel poly --degree 2 --gamma -1.6087"
"861  --dataset fashion-mnist --job_id 1585357 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.9676 --kernel poly --degree 1 --gamma 0.6271"
"513  --dataset fashion-mnist --job_id 1585357 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.3384 --kernel linear"
"464  --dataset fashion-mnist --job_id 1585357 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm SVM --C -2.3406 --kernel linear"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
