#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f5k10m-irace-val
#SBATCH --output=validation/cifar100-1f5k10m-irace-1586348-1586352/cifar100-1f5k10m-irace-1586348-val-%A-%a

CONFIGS=("738  --dataset cifar100 --job_id 1586348 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0143 --whiten False --svd_solver arpack --scaling False --algorithm KNeighbors --n_neighbors 17 --weights distance"
"934  --dataset cifar100 --job_id 1586348 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.017 --whiten False --svd_solver arpack --scaling False --algorithm KNeighbors --n_neighbors 26 --weights distance"
"931  --dataset cifar100 --job_id 1586348 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0151 --whiten False --svd_solver arpack --scaling False --algorithm KNeighbors --n_neighbors 24 --weights distance"
"600  --dataset cifar100 --job_id 1586348 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0123 --whiten False --svd_solver auto --scaling False --algorithm KNeighbors --n_neighbors 35 --weights distance"
"745  --dataset cifar100 --job_id 1586348 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0172 --whiten False --svd_solver auto --scaling False --algorithm KNeighbors --n_neighbors 7 --weights distance"
"774  --dataset cifar100 --job_id 1586348 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0129 --whiten False --svd_solver arpack --scaling False --algorithm KNeighbors --n_neighbors 19 --weights distance"
"802  --dataset cifar100 --job_id 1586348 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.018 --whiten False --svd_solver arpack --scaling False --algorithm KNeighbors --n_neighbors 8 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
