#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f5k10m-irace-val
#SBATCH --output=validation/cifar100-1f5k10m-irace-1586348-1586352/cifar100-1f5k10m-irace-1586352-val-%A-%a

CONFIGS=("854  --dataset cifar100 --job_id 1586352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0248 --whiten True --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 86 --scaling False --algorithm LogisticRegression --lr_C -2.6908 --lr_solver sag --multi_class multinomial --max_iter 580"
"803  --dataset cifar100 --job_id 1586352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0222 --whiten True --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 47 --scaling False --algorithm LogisticRegression --lr_C -1.0771 --lr_solver sag --multi_class multinomial --max_iter 539"
"769  --dataset cifar100 --job_id 1586352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0151 --whiten True --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 32 --scaling False --algorithm LogisticRegression --lr_C -0.4286 --lr_solver sag --multi_class multinomial --max_iter 930"
"837  --dataset cifar100 --job_id 1586352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0299 --whiten True --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 47 --scaling False --algorithm LogisticRegression --lr_C -1.0481 --lr_solver sag --multi_class multinomial --max_iter 925"
"619  --dataset cifar100 --job_id 1586352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.0508 --whiten True --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 29 --scaling False --algorithm LogisticRegression --lr_C -1.3202 --lr_solver sag --multi_class multinomial --max_iter 805"
"883  --dataset cifar100 --job_id 1586352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0215 --whiten True --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 63 --scaling False --algorithm LogisticRegression --lr_C -3.3011 --lr_solver sag --multi_class multinomial --max_iter 127"
"940  --dataset cifar100 --job_id 1586352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0274 --whiten True --svd_solver auto --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 95 --scaling False --algorithm LogisticRegression --lr_C -2.4833 --lr_solver sag --multi_class multinomial --max_iter 691"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
