#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1585133-1585137/cifar10-1f2k10m-irace-1585135-val-%A-%a

CONFIGS=("355  --dataset cifar10 --job_id 1585135 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 68 --scaling False --algorithm KNeighbors --n_neighbors 16 --weights distance"
"347  --dataset cifar10 --job_id 1585135 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C 1.927 --lr_solver newton-cg --multi_class multinomial --max_iter 637"
"353  --dataset cifar10 --job_id 1585135 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C 2.4148 --lr_solver newton-cg --multi_class multinomial --max_iter 776"
"349  --dataset cifar10 --job_id 1585135 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C 4.4333 --lr_solver newton-cg --multi_class multinomial --max_iter 462"
"352  --dataset cifar10 --job_id 1585135 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C 3.5709 --lr_solver newton-cg --multi_class multinomial --max_iter 398"
"357  --dataset cifar10 --job_id 1585135 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C 1.0797 --lr_solver newton-cg --multi_class multinomial --max_iter 664"
"345  --dataset cifar10 --job_id 1585135 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C 4.0262 --lr_solver newton-cg --multi_class multinomial --max_iter 540"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
