#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1585133-1585137/cifar10-1f2k10m-irace-1585136-val-%A-%a

CONFIGS=("203  --dataset cifar10 --job_id 1585136 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.1179 --lr_solver lbfgs --multi_class multinomial --max_iter 670"
"162  --dataset cifar10 --job_id 1585136 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2525 --lr_solver lbfgs --multi_class ovr --max_iter 118"
"173  --dataset cifar10 --job_id 1585136 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2558 --lr_solver lbfgs --multi_class multinomial --max_iter 613"
"257  --dataset cifar10 --job_id 1585136 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2624 --lr_solver lbfgs --multi_class multinomial --max_iter 110"
"338  --dataset cifar10 --job_id 1585136 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2111 --lr_solver lbfgs --multi_class ovr --max_iter 137"
"288  --dataset cifar10 --job_id 1585136 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.3421 --lr_solver lbfgs --multi_class multinomial --max_iter 993"
"212  --dataset cifar10 --job_id 1585136 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.388 --lr_solver lbfgs --multi_class multinomial --max_iter 228"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
