#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-3
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1585133-1585137/cifar10-1f2k10m-irace-1585134-val-%A-%a

CONFIGS=("322  --dataset cifar10 --job_id 1585134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.1156 --lr_solver lbfgs --multi_class multinomial --max_iter 554"
"345  --dataset cifar10 --job_id 1585134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.0555 --lr_solver lbfgs --multi_class multinomial --max_iter 854"
"338  --dataset cifar10 --job_id 1585134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.2327 --lr_solver lbfgs --multi_class multinomial --max_iter 557"
"358  --dataset cifar10 --job_id 1585134 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -3.1421 --lr_solver lbfgs --multi_class multinomial --max_iter 305"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
