#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1585133-1585137/cifar10-1f2k10m-irace-1585133-val-%A-%a

CONFIGS=("206  --dataset cifar10 --job_id 1585133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -2.8303 --lr_solver lbfgs --multi_class multinomial --max_iter 107"
"196  --dataset cifar10 --job_id 1585133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -0.9558 --lr_solver lbfgs --multi_class multinomial --max_iter 149"
"125  --dataset cifar10 --job_id 1585133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction FastICA --ext_components 0.0575 --ica_algorithm parallel --ica_fun cube --scaling True --algorithm MLP --solver lbfgs --alpha -2.9266 --hidden_layers 3 --neurons1 397 --neurons2 29 --neurons3 324 --activation identity"
"162  --dataset cifar10 --job_id 1585133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C -1.4573 --lr_solver lbfgs --multi_class multinomial --max_iter 192"
"130  --dataset cifar10 --job_id 1585133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm LogisticRegression --lr_C 0.1875 --lr_solver lbfgs --multi_class multinomial --max_iter 296"
"159  --dataset cifar10 --job_id 1585133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm KNeighbors --n_neighbors 87 --weights distance"
"349  --dataset cifar10 --job_id 1585133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -2.5887 --lr_solver lbfgs --multi_class multinomial --max_iter 523"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
