#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-5
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1585133-1585137/cifar10-1f2k10m-irace-1585137-val-%A-%a

CONFIGS=("246  --dataset cifar10 --job_id 1585137 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling False --extraction PCA --ext_components 0.0397 --whiten False --svd_solver auto --scaling True --algorithm MLP --solver sgd --alpha -0.358 --mlp_learning_rate adaptive --learning_rate_init -2.008 --hidden_layers 1 --neurons1 274 --activation relu"
"301  --dataset cifar10 --job_id 1585137 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0194 --whiten False --svd_solver randomized --scaling False --algorithm MLP --solver lbfgs --alpha 1.208 --hidden_layers 1 --neurons1 90 --activation identity"
"336  --dataset cifar10 --job_id 1585137 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0815 --whiten False --svd_solver randomized --scaling False --algorithm MLP --solver lbfgs --alpha 2.7344 --hidden_layers 1 --neurons1 197 --activation identity"
"209  --dataset cifar10 --job_id 1585137 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0997 --whiten False --svd_solver randomized --scaling False --algorithm MLP --solver lbfgs --alpha 2.0522 --hidden_layers 1 --neurons1 66 --activation identity"
"356  --dataset cifar10 --job_id 1585137 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0114 --whiten False --svd_solver randomized --scaling False --algorithm MLP --solver lbfgs --alpha -1.0289 --hidden_layers 1 --neurons1 116 --activation identity"
"364  --dataset cifar10 --job_id 1585137 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 none --pre_scaling True --extraction PCA --ext_components 0.0251 --whiten False --svd_solver randomized --scaling False --algorithm MLP --solver lbfgs --alpha 1.9611 --hidden_layers 1 --neurons1 48 --activation identity"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
