#!/bin/bash
#SBATCH --time=0-8:40
#SBATCH --job-name=vsvhn-fdef
#SBATCH --cpus-per-task=1
#SBATCH --mem=64G
#SBATCH --output=svhn-fdef-val_%j.out
#

srun python /home/cemvieira/isklearn/svhn/validation.py  --task classification --sparse False --f_eng1 None --f_eng2 None --pre_scaling False --scaling False --algorithm SVM --C 1 --kernel poly --degree 3