#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1540451-1540455/cifar10-1f2k10m-irace-1540451-val-%A-%a

CONFIGS=("320  --dataset cifar10 --job_id 1540451 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.1116 --lr_solver newton-cg --multi_class multinomial --max_iter 515"
"293  --dataset cifar10 --job_id 1540451 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2182 --lr_solver newton-cg --multi_class multinomial --max_iter 600"
"326  --dataset cifar10 --job_id 1540451 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4479 --lr_solver newton-cg --multi_class multinomial --max_iter 572"
"290  --dataset cifar10 --job_id 1540451 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.0977 --lr_solver newton-cg --multi_class multinomial --max_iter 919"
"195  --dataset cifar10 --job_id 1540451 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.3124 --lr_solver newton-cg --multi_class multinomial --max_iter 213"
"304  --dataset cifar10 --job_id 1540451 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2965 --lr_solver newton-cg --multi_class multinomial --max_iter 651"
"331  --dataset cifar10 --job_id 1540451 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4021 --lr_solver newton-cg --multi_class multinomial --max_iter 319"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
