#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1540451-1540455/cifar10-1f2k10m-irace-1540452-val-%A-%a

CONFIGS=("271  --dataset cifar10 --job_id 1540452 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 3.1017 --kernel rbf --gamma -3.2515"
"292  --dataset cifar10 --job_id 1540452 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 1.82 --kernel rbf --gamma -3.7075"
"315  --dataset cifar10 --job_id 1540452 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 2.3095 --kernel rbf --gamma -3.4659"
"353  --dataset cifar10 --job_id 1540452 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 4.1643 --kernel rbf --gamma -3.3889"
"346  --dataset cifar10 --job_id 1540452 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 4.901 --kernel rbf --gamma -3.2632"
"320  --dataset cifar10 --job_id 1540452 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 3.1745 --kernel rbf --gamma -3.6391"
"371  --dataset cifar10 --job_id 1540452 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C 0.5415 --kernel rbf --gamma -3.53"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
