#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1540451-1540455/cifar10-1f2k10m-irace-1540453-val-%A-%a

CONFIGS=("309  --dataset cifar10 --job_id 1540453 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2703 --lr_solver newton-cg --multi_class multinomial --max_iter 857"
"341  --dataset cifar10 --job_id 1540453 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4651 --lr_solver newton-cg --multi_class multinomial --max_iter 542"
"348  --dataset cifar10 --job_id 1540453 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4246 --lr_solver newton-cg --multi_class multinomial --max_iter 360"
"273  --dataset cifar10 --job_id 1540453 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.1114 --lr_solver newton-cg --multi_class multinomial --max_iter 575"
"318  --dataset cifar10 --job_id 1540453 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2482 --lr_solver newton-cg --multi_class multinomial --max_iter 792"
"281  --dataset cifar10 --job_id 1540453 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.0866 --lr_solver newton-cg --multi_class multinomial --max_iter 378"
"225  --dataset cifar10 --job_id 1540453 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.1028 --lr_solver newton-cg --multi_class multinomial --max_iter 385"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
