#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1540451-1540455/cifar10-1f2k10m-irace-1540454-val-%A-%a

CONFIGS=("278  --dataset cifar10 --job_id 1540454 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -3.085 --kernel linear"
"287  --dataset cifar10 --job_id 1540454 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -3.1141 --kernel linear"
"358  --dataset cifar10 --job_id 1540454 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -3.0351 --kernel linear"
"357  --dataset cifar10 --job_id 1540454 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -3.0661 --kernel linear"
"220  --dataset cifar10 --job_id 1540454 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C -3.2859 --kernel linear"
"316  --dataset cifar10 --job_id 1540454 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -3.0268 --kernel linear"
"288  --dataset cifar10 --job_id 1540454 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C -3.2724 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
