#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-4
#SBATCH --job-name=cifar10-1f2k10m-irace-val
#SBATCH --output=validation/cifar10-1f2k10m-irace-1540451-1540455/cifar10-1f2k10m-irace-1540455-val-%A-%a

CONFIGS=("201  --dataset cifar10 --job_id 1540455 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2059 --lr_solver lbfgs --multi_class multinomial --max_iter 797"
"334  --dataset cifar10 --job_id 1540455 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.2674 --lr_solver lbfgs --multi_class ovr --max_iter 851"
"335  --dataset cifar10 --job_id 1540455 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -2.9883 --lr_solver lbfgs --multi_class multinomial --max_iter 326"
"352  --dataset cifar10 --job_id 1540455 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4219 --lr_solver lbfgs --multi_class multinomial --max_iter 805"
"363  --dataset cifar10 --job_id 1540455 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -3.4141 --lr_solver lbfgs --multi_class multinomial --max_iter 350"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
