#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=svhn-1f5k10m-irace-val
#SBATCH --output=validation/svhn-1f5k10m-irace-1547599-1547603/svhn-1f5k10m-irace-1547601-val-%A-%a

CONFIGS=("758  --dataset svhn --job_id 1547601 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm KNeighbors --n_neighbors 10 --weights distance"
"717  --dataset svhn --job_id 1547601 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm KNeighbors --n_neighbors 9 --weights distance"
"467  --dataset svhn --job_id 1547601 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 12 --weights distance"
"808  --dataset svhn --job_id 1547601 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm KNeighbors --n_neighbors 8 --weights distance"
"837  --dataset svhn --job_id 1547601 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm KNeighbors --n_neighbors 7 --weights distance"
"949  --dataset svhn --job_id 1547601 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm KNeighbors --n_neighbors 11 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
