#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-4
#SBATCH --job-name=svhn-1f5k10m-irace-val
#SBATCH --output=validation/svhn-1f5k10m-irace-1547599-1547603/svhn-1f5k10m-irace-1547603-val-%A-%a

CONFIGS=("926  --dataset svhn --job_id 1547603 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 12 --weights distance"
"797  --dataset svhn --job_id 1547603 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 11 --weights distance"
"940  --dataset svhn --job_id 1547603 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 13 --weights distance"
"934  --dataset svhn --job_id 1547603 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 19 --weights distance"
"941  --dataset svhn --job_id 1547603 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 14 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
