#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=svhn-1f5k10m-irace-val
#SBATCH --output=validation/svhn-1f5k10m-irace-1547599-1547603/svhn-1f5k10m-irace-1547599-val-%A-%a

CONFIGS=("799  --dataset svhn --job_id 1547599 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0133 --whiten False --svd_solver randomized --scaling True --algorithm KNeighbors --n_neighbors 24 --weights uniform"
"679  --dataset svhn --job_id 1547599 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0115 --whiten False --svd_solver randomized --scaling True --algorithm KNeighbors --n_neighbors 32 --weights uniform"
"901  --dataset svhn --job_id 1547599 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.016 --whiten False --svd_solver randomized --scaling True --algorithm KNeighbors --n_neighbors 30 --weights uniform"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
