#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-1
#SBATCH --job-name=svhn-1f5k10m-irace-val
#SBATCH --output=validation/svhn-1f5k10m-irace-1547599-1547603/svhn-1f5k10m-irace-1547600-val-%A-%a

CONFIGS=("908  --dataset svhn --job_id 1547600 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0188 --whiten True --svd_solver arpack --scaling True --algorithm MLP --solver lbfgs --alpha -3.8832 --hidden_layers 2 --neurons1 178 --neurons2 309 --activation relu"
"924  --dataset svhn --job_id 1547600 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.0248 --whiten True --svd_solver arpack --scaling True --algorithm MLP --solver lbfgs --alpha -2.2127 --hidden_layers 1 --neurons1 363 --activation relu"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
