#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1585349-1585353/fashion-mnist-1f2k10m-irace-1585349-val-%A-%a

CONFIGS=("318  --dataset fashion-mnist --job_id 1585349 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.8585 --whiten False --svd_solver randomized --scaling False --algorithm SVM --C -0.383 --kernel poly --degree 2 --gamma -3.8679"
"313  --dataset fashion-mnist --job_id 1585349 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.5985 --whiten False --svd_solver randomized --scaling False --algorithm SVM --C 4.298 --kernel poly --degree 2 --gamma -3.3883"
"322  --dataset fashion-mnist --job_id 1585349 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.7088 --whiten False --svd_solver randomized --scaling False --algorithm SVM --C 1.0874 --kernel poly --degree 2 --gamma -1.667"
"331  --dataset fashion-mnist --job_id 1585349 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.3533 --whiten False --svd_solver randomized --scaling False --algorithm SVM --C 0.8565 --kernel poly --degree 3 --gamma -3.7677"
"274  --dataset fashion-mnist --job_id 1585349 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.2582 --whiten False --svd_solver randomized --scaling False --algorithm SVM --C 2.5148 --kernel poly --degree 3 --gamma -1.4019"
"325  --dataset fashion-mnist --job_id 1585349 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.3381 --whiten False --svd_solver randomized --scaling False --algorithm SVM --C -1.2215 --kernel poly --degree 3 --gamma 0.5213"
"337  --dataset fashion-mnist --job_id 1585349 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.3779 --whiten False --svd_solver randomized --scaling False --algorithm SVM --C -1.5045 --kernel poly --degree 3 --gamma -4.9053"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
