#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-4
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1585349-1585353/fashion-mnist-1f2k10m-irace-1585352-val-%A-%a

CONFIGS=("251  --dataset fashion-mnist --job_id 1585352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 1.0861 --kernel rbf --gamma -2.2985"
"341  --dataset fashion-mnist --job_id 1585352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 3.0711 --kernel rbf --gamma -2.6094"
"350  --dataset fashion-mnist --job_id 1585352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 0.8077 --kernel rbf --gamma -2.7215"
"347  --dataset fashion-mnist --job_id 1585352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 1.1205 --kernel rbf --gamma -3.0015"
"371  --dataset fashion-mnist --job_id 1585352 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 4.8111 --kernel rbf --gamma -2.2975"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
