#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-1f2k10m-irace-val
#SBATCH --output=validation/fashion-mnist-1f2k10m-irace-1585349-1585353/fashion-mnist-1f2k10m-irace-1585351-val-%A-%a

CONFIGS=("15   --dataset fashion-mnist --job_id 1585351 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.8567 --lr_solver newton-cg --multi_class multinomial --max_iter 326"
"266  --dataset fashion-mnist --job_id 1585351 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.8515 --lr_solver newton-cg --multi_class multinomial --max_iter 377"
"257  --dataset fashion-mnist --job_id 1585351 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.987 --lr_solver newton-cg --multi_class multinomial --max_iter 534"
"320  --dataset fashion-mnist --job_id 1585351 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.9295 --lr_solver newton-cg --multi_class multinomial --max_iter 571"
"286  --dataset fashion-mnist --job_id 1585351 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.8892 --lr_solver newton-cg --multi_class multinomial --max_iter 154"
"364  --dataset fashion-mnist --job_id 1585351 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.7741 --lr_solver newton-cg --multi_class multinomial --max_iter 518"
"273  --dataset fashion-mnist --job_id 1585351 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling True --algorithm LogisticRegression --lr_C -1.7613 --lr_solver newton-cg --multi_class multinomial --max_iter 441"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
