#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=fashion-mnist-3f2k30m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k30m-irace-1545505-1545509/fashion-mnist-3f2k30m-irace-1545508-val-%A-%a

CONFIGS=("200  --dataset fashion-mnist --job_id 1545508 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1654 --kernel linear"
"257  --dataset fashion-mnist --job_id 1545508 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1748 --kernel linear"
"160  --dataset fashion-mnist --job_id 1545508 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.343 --kernel linear"
"132  --dataset fashion-mnist --job_id 1545508 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.3452 --kernel linear"
"240  --dataset fashion-mnist --job_id 1545508 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1363 --kernel linear"
"330  --dataset fashion-mnist --job_id 1545508 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm SVM --C -2.1116 --kernel linear"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
