#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k30m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k30m-irace-1545505-1545509/fashion-mnist-3f2k30m-irace-1545509-val-%A-%a

CONFIGS=("242  --dataset fashion-mnist --job_id 1545509 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.6716 --lr_solver lbfgs --multi_class ovr --max_iter 331"
"266  --dataset fashion-mnist --job_id 1545509 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.4761 --lr_solver lbfgs --multi_class ovr --max_iter 471"
"243  --dataset fashion-mnist --job_id 1545509 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -0.9989 --lr_solver lbfgs --multi_class ovr --max_iter 306"
"221  --dataset fashion-mnist --job_id 1545509 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -2.526 --lr_solver newton-cg --multi_class ovr --max_iter 185"
"115  --dataset fashion-mnist --job_id 1545509 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction FastICA --ext_components 0.1204 --ica_algorithm deflation --ica_fun cube --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm LogisticRegression --lr_C -0.7893 --lr_solver newton-cg --multi_class multinomial --max_iter 699"
"194  --dataset fashion-mnist --job_id 1545509 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -2.5572 --lr_solver newton-cg --multi_class ovr --max_iter 203"
"332  --dataset fashion-mnist --job_id 1545509 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm LogisticRegression --lr_C -1.4958 --lr_solver lbfgs --multi_class ovr --max_iter 312"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
