#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k30m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k30m-irace-1545505-1545509/fashion-mnist-3f2k30m-irace-1545507-val-%A-%a

CONFIGS=("310  --dataset fashion-mnist --job_id 1545507 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm LogisticRegression --lr_C -1.8546 --lr_solver newton-cg --multi_class multinomial --max_iter 536"
"218  --dataset fashion-mnist --job_id 1545507 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm LogisticRegression --lr_C -1.9691 --lr_solver newton-cg --multi_class multinomial --max_iter 444"
"94   --dataset fashion-mnist --job_id 1545507 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm LogisticRegression --lr_C -1.6891 --lr_solver newton-cg --multi_class multinomial --max_iter 370"
"7    --dataset fashion-mnist --job_id 1545507 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 None --pre_scaling False --extraction PCA --ext_components 0.177 --whiten False --svd_solver full --scaling True --algorithm LogisticRegression --lr_C -1.2831 --lr_solver lbfgs --multi_class multinomial --max_iter 549"
"58   --dataset fashion-mnist --job_id 1545507 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectFromModel --sel_model SVM --sel_threshold mean --scaling True --algorithm LogisticRegression --lr_C -2.4388 --lr_solver newton-cg --multi_class multinomial --max_iter 895"
"64   --dataset fashion-mnist --job_id 1545507 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm SVM --C 0.8738 --kernel poly --degree 4 --gamma 0.2786"
"349  --dataset fashion-mnist --job_id 1545507 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model DecisionTree --sel_threshold median --scaling False --algorithm LogisticRegression --lr_C -1.8713 --lr_solver newton-cg --multi_class multinomial --max_iter 513"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
