#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=fashion-mnist-3f2k30m-irace-val
#SBATCH --output=validation/fashion-mnist-3f2k30m-irace-1545505-1545509/fashion-mnist-3f2k30m-irace-1545505-val-%A-%a

CONFIGS=("308  --dataset fashion-mnist --job_id 1545505 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.1546 --whiten False --svd_solver arpack --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 1.0772 --kernel rbf --gamma -2.0469"
"177  --dataset fashion-mnist --job_id 1545505 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.1772 --whiten False --svd_solver arpack --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling True --algorithm SVM --C 0.6858 --kernel rbf --gamma -1.6018"
"81   --dataset fashion-mnist --job_id 1545505 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.2893 --whiten False --svd_solver arpack --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C -0.1209 --kernel rbf --gamma -2.3172"
"97   --dataset fashion-mnist --job_id 1545505 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling False --extraction PCA --ext_components 0.0303 --whiten False --svd_solver randomized --selection RFE --sel_model RandomForest --sel_percentile 85 --scaling True --algorithm KNeighbors --n_neighbors 10 --weights distance"
"96   --dataset fashion-mnist --job_id 1545505 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm KNeighbors --n_neighbors 6 --weights uniform"
"1    --dataset fashion-mnist --job_id 1545505 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Extraction --f_eng2 Selection --pre_scaling True --extraction PCA --ext_components 0.4466 --whiten True --svd_solver randomized --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm SVM --C 3.8612 --kernel linear"
"44   --dataset fashion-mnist --job_id 1545505 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 40 --weights uniform"
)

srun python /home/cemvieira/isklearn/fashion-mnist/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
