#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=svhn-3f5k15m-irace-val
#SBATCH --output=validation/svhn-3f5k15m-irace-1547584-1547588/svhn-3f5k15m-irace-1547586-val-%A-%a

CONFIGS=("938  --dataset svhn --job_id 1547586 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling False --algorithm KNeighbors --n_neighbors 7 --weights uniform"
"898  --dataset svhn --job_id 1547586 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 30 --scaling False --algorithm KNeighbors --n_neighbors 7 --weights uniform"
"863  --dataset svhn --job_id 1547586 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 16 --scaling False --algorithm KNeighbors --n_neighbors 11 --weights uniform"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
