#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-3f5k15m-irace-val
#SBATCH --output=validation/svhn-3f5k15m-irace-1547584-1547588/svhn-3f5k15m-irace-1547587-val-%A-%a

CONFIGS=("746  --dataset svhn --job_id 1547587 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 9 --weights uniform"
"811  --dataset svhn --job_id 1547587 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 16 --weights uniform"
"333  --dataset svhn --job_id 1547587 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.3069 --max_depth none --max_depth_value 2 --min_samples_leaf 0.0124"
"559  --dataset svhn --job_id 1547587 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.3803 --max_depth value --max_depth_value 27 --min_samples_leaf 0.0143"
"884  --dataset svhn --job_id 1547587 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 39 --weights uniform"
"934  --dataset svhn --job_id 1547587 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.4511 --max_depth value --max_depth_value 31 --min_samples_leaf 0.0348"
"938  --dataset svhn --job_id 1547587 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm KNeighbors --n_neighbors 13 --weights uniform"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
