#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-3f5k15m-irace-val
#SBATCH --output=validation/svhn-3f5k15m-irace-1547584-1547588/svhn-3f5k15m-irace-1547585-val-%A-%a

CONFIGS=("901  --dataset svhn --job_id 1547585 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.4822 --max_depth none --max_depth_value 28 --min_samples_leaf 0.0119"
"885  --dataset svhn --job_id 1547585 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification entropy --max_features 0.6658 --max_depth value --max_depth_value 33 --min_samples_leaf 0.0111"
"435  --dataset svhn --job_id 1547585 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.6048 --max_depth value --max_depth_value 27 --min_samples_leaf 0.0118"
"537  --dataset svhn --job_id 1547585 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification entropy --max_features 0.4049 --max_depth value --max_depth_value 30 --min_samples_leaf 0.0105"
"221  --dataset svhn --job_id 1547585 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.4382 --max_depth none --max_depth_value 31 --min_samples_leaf 0.0125"
"558  --dataset svhn --job_id 1547585 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm DecisionTree --criterion_classification gini --max_features 0.1571 --max_depth none --max_depth_value 23 --min_samples_leaf 0.0105"
"775  --dataset svhn --job_id 1547585 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling False --algorithm DecisionTree --criterion_classification entropy --max_features 0.4798 --max_depth none --max_depth_value 16 --min_samples_leaf 0.0126"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
