#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1554129-1554133/cifar100-1f2k10m-irace-1554130-val-%A-%a

CONFIGS=("368  --dataset cifar100 --job_id 1554130 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.2054 --whiten False --svd_solver full --scaling False --algorithm MLP --solver lbfgs --alpha -1.7324 --hidden_layers 1 --neurons1 189 --activation relu"
"370  --dataset cifar100 --job_id 1554130 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.8025 --whiten False --svd_solver full --scaling False --algorithm MLP --solver lbfgs --alpha -1.9959 --hidden_layers 2 --neurons1 191 --neurons2 369 --activation relu"
"360  --dataset cifar100 --job_id 1554130 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 39 --scaling True --algorithm MLP --solver adam --alpha -0.2797 --learning_rate_init -1.9643 --hidden_layers 1 --neurons1 235 --activation logistic"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
