#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1554129-1554133/cifar100-1f2k10m-irace-1554133-val-%A-%a

CONFIGS=("319  --dataset cifar100 --job_id 1554133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 92 --scaling False --algorithm SVM --C 0.5331 --kernel linear"
"313  --dataset cifar100 --job_id 1554133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 81 --scaling False --algorithm SVM --C -0.9293 --kernel linear"
"308  --dataset cifar100 --job_id 1554133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 81 --scaling True --algorithm SVM --C 1.0282 --kernel linear"
"338  --dataset cifar100 --job_id 1554133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 86 --scaling False --algorithm SVM --C 1.098 --kernel linear"
"326  --dataset cifar100 --job_id 1554133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 85 --scaling False --algorithm SVM --C 2.7841 --kernel linear"
"318  --dataset cifar100 --job_id 1554133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 92 --scaling True --algorithm SVM --C 4.5784 --kernel linear"
"212  --dataset cifar100 --job_id 1554133 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 43 --scaling True --algorithm SVM --C -2.632 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
