#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1554129-1554133/cifar100-1f2k10m-irace-1554131-val-%A-%a

CONFIGS=("134  --dataset cifar100 --job_id 1554131 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 65 --scaling True --algorithm KNeighbors --n_neighbors 12 --weights distance"
"260  --dataset cifar100 --job_id 1554131 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 61 --scaling True --algorithm KNeighbors --n_neighbors 19 --weights distance"
"130  --dataset cifar100 --job_id 1554131 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 52 --scaling True --algorithm KNeighbors --n_neighbors 25 --weights distance"
"256  --dataset cifar100 --job_id 1554131 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 50 --scaling True --algorithm KNeighbors --n_neighbors 18 --weights distance"
"289  --dataset cifar100 --job_id 1554131 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 65 --scaling True --algorithm KNeighbors --n_neighbors 16 --weights distance"
"205  --dataset cifar100 --job_id 1554131 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 80 --scaling True --algorithm KNeighbors --n_neighbors 10 --weights distance"
"110  --dataset cifar100 --job_id 1554131 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 64 --scaling False --algorithm KNeighbors --n_neighbors 14 --weights distance"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
