#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-1f2k10m-irace-val
#SBATCH --output=validation/cifar100-1f2k10m-irace-1554129-1554133/cifar100-1f2k10m-irace-1554129-val-%A-%a

CONFIGS=("344  --dataset cifar100 --job_id 1554129 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 97 --scaling False --algorithm SVM --C -3.8237 --kernel poly --degree 2 --gamma -2.2232"
"354  --dataset cifar100 --job_id 1554129 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 89 --scaling False --algorithm SVM --C 4.7851 --kernel poly --degree 2 --gamma -4.1825"
"313  --dataset cifar100 --job_id 1554129 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 87 --scaling False --algorithm SVM --C -1.0041 --kernel poly --degree 2 --gamma -3.3407"
"290  --dataset cifar100 --job_id 1554129 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 71 --scaling False --algorithm SVM --C -1.7738 --kernel poly --degree 1 --gamma -4.0077"
"314  --dataset cifar100 --job_id 1554129 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 88 --scaling False --algorithm SVM --C 2.5557 --kernel poly --degree 2 --gamma -2.0174"
"305  --dataset cifar100 --job_id 1554129 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 79 --scaling False --algorithm SVM --C 2.33 --kernel linear"
"356  --dataset cifar100 --job_id 1554129 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 99 --scaling False --algorithm SVM --C -0.1017 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
