#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-0
#SBATCH --job-name=svhn-3f2k30m-irace-val
#SBATCH --output=validation/svhn-3f2k30m-irace-1547589-1547593/svhn-3f2k30m-irace-1547590-val-%A-%a

CONFIGS=("336  --dataset svhn --job_id 1547590 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.013 --whiten True --svd_solver full --scaling True --algorithm KNeighbors --n_neighbors 37 --weights uniform"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
