#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-5
#SBATCH --job-name=svhn-3f2k30m-irace-val
#SBATCH --output=validation/svhn-3f2k30m-irace-1547589-1547593/svhn-3f2k30m-irace-1547593-val-%A-%a

CONFIGS=("265  --dataset svhn --job_id 1547593 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 28 --scaling False --algorithm KNeighbors --n_neighbors 11 --weights distance"
"296  --dataset svhn --job_id 1547593 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 24 --scaling True --algorithm KNeighbors --n_neighbors 13 --weights distance"
"279  --dataset svhn --job_id 1547593 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 28 --scaling True --algorithm KNeighbors --n_neighbors 13 --weights distance"
"319  --dataset svhn --job_id 1547593 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 31 --scaling False --algorithm KNeighbors --n_neighbors 8 --weights distance"
"350  --dataset svhn --job_id 1547593 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 22 --scaling True --algorithm KNeighbors --n_neighbors 14 --weights distance"
"355  --dataset svhn --job_id 1547593 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling True --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 24 --scaling False --algorithm KNeighbors --n_neighbors 17 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
