#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=svhn-3f2k30m-irace-val
#SBATCH --output=validation/svhn-3f2k30m-irace-1547589-1547593/svhn-3f2k30m-irace-1547589-val-%A-%a

CONFIGS=("337  --dataset svhn --job_id 1547589 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 2.6687 --kernel rbf --gamma -3.8881"
"344  --dataset svhn --job_id 1547589 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 3.2736 --kernel rbf --gamma -3.2775"
"362  --dataset svhn --job_id 1547589 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 None --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm SVM --C 3.4032 --kernel rbf --gamma -2.8401"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
