#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-3f5k15m-irace-val
#SBATCH --output=validation/svhn-3f5k15m-irace-1585218-1585222/svhn-3f5k15m-irace-1585221-val-%A-%a

CONFIGS=("832  --dataset svhn --job_id 1585221 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 27 --weights distance"
"883  --dataset svhn --job_id 1585221 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction PCA --ext_components 0.3271 --whiten False --svd_solver auto --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 15 --weights distance"
"911  --dataset svhn --job_id 1585221 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 21 --weights distance"
"929  --dataset svhn --job_id 1585221 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"928  --dataset svhn --job_id 1585221 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 13 --weights distance"
"931  --dataset svhn --job_id 1585221 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling False --algorithm KNeighbors --n_neighbors 24 --weights distance"
"947  --dataset svhn --job_id 1585221 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm KNeighbors --n_neighbors 17 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
