#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-1
#SBATCH --job-name=svhn-3f5k15m-irace-val
#SBATCH --output=validation/svhn-3f5k15m-irace-1585218-1585222/svhn-3f5k15m-irace-1585222-val-%A-%a

CONFIGS=("889  --dataset svhn --job_id 1585222 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0543 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 51 --scaling False --algorithm KNeighbors --n_neighbors 12 --weights distance"
"945  --dataset svhn --job_id 1585222 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.1864 --ica_algorithm deflation --ica_fun cube --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 8 --scaling False --algorithm KNeighbors --n_neighbors 17 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
