#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-3f5k15m-irace-val
#SBATCH --output=validation/svhn-3f5k15m-irace-1585218-1585222/svhn-3f5k15m-irace-1585219-val-%A-%a

CONFIGS=("894  --dataset svhn --job_id 1585219 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 32 --weights distance"
"912  --dataset svhn --job_id 1585219 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 5 --weights distance"
"924  --dataset svhn --job_id 1585219 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.1079 --max_depth none --max_depth_value 40 --min_samples_leaf 0.1734"
"918  --dataset svhn --job_id 1585219 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 4 --scaling False --algorithm DecisionTree --criterion_classification entropy --max_features 0.3249 --max_depth value --max_depth_value 2 --min_samples_leaf 0.0963"
"925  --dataset svhn --job_id 1585219 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm MLP --solver lbfgs --alpha -0.1765 --hidden_layers 3 --neurons1 152 --neurons2 144 --neurons3 96 --activation identity"
"938  --dataset svhn --job_id 1585219 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 19 --weights distance"
"950  --dataset svhn --job_id 1585219 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm KNeighbors --n_neighbors 23 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
