#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-3f5k15m-irace-val
#SBATCH --output=validation/svhn-3f5k15m-irace-1585218-1585222/svhn-3f5k15m-irace-1585218-val-%A-%a

CONFIGS=("567  --dataset svhn --job_id 1585218 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.6514 --max_depth none --max_depth_value 5 --min_samples_leaf 0.011"
"912  --dataset svhn --job_id 1585218 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.9835 --max_depth none --max_depth_value 4 --min_samples_leaf 0.0134"
"495  --dataset svhn --job_id 1585218 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.549 --max_depth none --max_depth_value 8 --min_samples_leaf 0.0128"
"728  --dataset svhn --job_id 1585218 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.8615 --max_depth none --max_depth_value 6 --min_samples_leaf 0.013"
"717  --dataset svhn --job_id 1585218 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.216 --max_depth none --max_depth_value 19 --min_samples_leaf 0.0141"
"267  --dataset svhn --job_id 1585218 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.2572 --max_depth none --max_depth_value 2 --min_samples_leaf 0.081"
"260  --dataset svhn --job_id 1585218 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 none --scaling False --algorithm DecisionTree --criterion_classification gini --max_features 0.3669 --max_depth value --max_depth_value 10 --min_samples_leaf 0.1198"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
