#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=svhn-1f2k10m-irace-val
#SBATCH --output=validation/svhn-1f2k10m-irace-1585428/svhn-1f2k10m-irace-1585428-val-%A-%a

CONFIGS=("302  --dataset svhn --job_id 1585428 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 28 --scaling True --algorithm KNeighbors --n_neighbors 10 --weights distance"
"182  --dataset svhn --job_id 1585428 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 26 --scaling True --algorithm KNeighbors --n_neighbors 7 --weights distance"
"187  --dataset svhn --job_id 1585428 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 25 --scaling False --algorithm KNeighbors --n_neighbors 12 --weights distance"
"268  --dataset svhn --job_id 1585428 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 30 --scaling True --algorithm KNeighbors --n_neighbors 8 --weights distance"
"337  --dataset svhn --job_id 1585428 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 21 --scaling False --algorithm KNeighbors --n_neighbors 10 --weights distance"
"228  --dataset svhn --job_id 1585428 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 23 --scaling False --algorithm KNeighbors --n_neighbors 12 --weights distance"
"353  --dataset svhn --job_id 1585428 --cutoff 10 --metafolds 1 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 32 --scaling True --algorithm KNeighbors --n_neighbors 8 --weights distance"
)

srun python /home/cemvieira/isklearn/svhn/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
