#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-2
#SBATCH --job-name=cifar10-3f5k15m-irace-val
#SBATCH --output=validation/cifar10-3f5k15m-irace-1540441-1540445/cifar10-3f5k15m-irace-1540445-val-%A-%a

CONFIGS=("696  --dataset cifar10 --job_id 1540445 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 90 --scaling False --algorithm RandomForest --rf_estimators 207 --criterion_classification gini --max_features 0.188 --max_depth value --max_depth_value 47 --min_samples_leaf 0.0108"
"728  --dataset cifar10 --job_id 1540445 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 91 --scaling False --algorithm RandomForest --rf_estimators 223 --criterion_classification gini --max_features 0.1588 --max_depth value --max_depth_value 15 --min_samples_leaf 0.0119"
"934  --dataset cifar10 --job_id 1540445 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 Selection --pre_scaling False --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 84 --scaling False --algorithm RandomForest --rf_estimators 407 --criterion_classification gini --max_features 0.2977 --max_depth value --max_depth_value 35 --min_samples_leaf 0.0132"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
