#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-1
#SBATCH --job-name=cifar10-3f5k15m-irace-val
#SBATCH --output=validation/cifar10-3f5k15m-irace-1540441-1540445/cifar10-3f5k15m-irace-1540442-val-%A-%a

CONFIGS=("907  --dataset cifar10 --job_id 1540442 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm RandomForest --rf_estimators 242 --criterion_classification gini --max_features 0.2214 --max_depth value --max_depth_value 32 --min_samples_leaf 0.0121"
"951  --dataset cifar10 --job_id 1540442 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 None --f_eng2 None --scaling True --algorithm RandomForest --rf_estimators 308 --criterion_classification gini --max_features 0.3034 --max_depth value --max_depth_value 22 --min_samples_leaf 0.014"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
