#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH --array=0-6
#SBATCH --job-name=cifar10-3f5k15m-irace-val
#SBATCH --output=validation/cifar10-3f5k15m-irace-1540441-1540445/cifar10-3f5k15m-irace-1540444-val-%A-%a

CONFIGS=("408  --dataset cifar10 --job_id 1540444 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0108 --ica_algorithm deflation --ica_fun exp --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 65 --scaling True --algorithm KNeighbors --n_neighbors 31 --weights uniform"
"62   --dataset cifar10 --job_id 1540444 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0228 --whiten False --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 70 --scaling False --algorithm KNeighbors --n_neighbors 54 --weights distance"
"509  --dataset cifar10 --job_id 1540444 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0124 --ica_algorithm parallel --ica_fun exp --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 24 --scaling True --algorithm KNeighbors --n_neighbors 56 --weights uniform"
"942  --dataset cifar10 --job_id 1540444 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.0195 --ica_algorithm deflation --ica_fun exp --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 44 --scaling True --algorithm KNeighbors --n_neighbors 14 --weights uniform"
"620  --dataset cifar10 --job_id 1540444 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling True --extraction PCA --ext_components 0.0242 --whiten False --svd_solver arpack --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 26 --scaling False --algorithm KNeighbors --n_neighbors 63 --weights distance"
"622  --dataset cifar10 --job_id 1540444 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.1184 --ica_algorithm deflation --ica_fun exp --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 4 --scaling True --algorithm KNeighbors --n_neighbors 38 --weights uniform"
"533  --dataset cifar10 --job_id 1540444 --cutoff 15 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 Extraction --pre_scaling False --extraction FastICA --ext_components 0.1789 --ica_algorithm deflation --ica_fun exp --selection SelectPercentile --sel_score_classification f_classif --sel_percentile 6 --scaling True --algorithm KNeighbors --n_neighbors 76 --weights uniform"
)

srun python /home/cemvieira/isklearn/cifar10/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
