#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-6
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1586338-1586342/cifar100-3f2k30m-irace-1586340-val-%A-%a

CONFIGS=("234  --dataset cifar100 --job_id 1586340 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C 1.5966 --kernel linear"
"229  --dataset cifar100 --job_id 1586340 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C 2.2157 --kernel linear"
"232  --dataset cifar100 --job_id 1586340 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -0.265 --kernel linear"
"268  --dataset cifar100 --job_id 1586340 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -2.3808 --kernel linear"
"256  --dataset cifar100 --job_id 1586340 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -2.2649 --kernel linear"
"290  --dataset cifar100 --job_id 1586340 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -2.5652 --kernel linear"
"335  --dataset cifar100 --job_id 1586340 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm SVM --C -2.1152 --kernel linear"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
