#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-0
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1586338-1586342/cifar100-3f2k30m-irace-1586338-val-%A-%a

CONFIGS=("333  --dataset cifar100 --job_id 1586338 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 Selection --f_eng2 none --pre_scaling False --selection SelectFromModel --sel_model RandomForest --sel_threshold median --scaling True --algorithm LogisticRegression --lr_C -1.5679 --lr_solver newton-cg --multi_class multinomial --max_iter 379"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
