#!/bin/bash
#SBATCH --time=1-0:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16G
#SBATCH --array=0-0
#SBATCH --job-name=cifar100-3f2k30m-irace-val
#SBATCH --output=validation/cifar100-3f2k30m-irace-1586338-1586342/cifar100-3f2k30m-irace-1586342-val-%A-%a

CONFIGS=("365  --dataset cifar100 --job_id 1586342 --cutoff 30 --metafolds 3 --task classification --sparse False --f_eng1 none --f_eng2 Selection --pre_scaling True --selection SelectFromModel --sel_model RandomForest --sel_threshold mean --scaling False --algorithm RandomForest --rf_estimators 94 --criterion_classification gini --max_features 0.0716 --max_depth none --min_samples_leaf 0.0126"
)

srun python /home/cemvieira/isklearn/cifar100/validation.py ${CONFIGS[$SLURM_ARRAY_TASK_ID]}
